/*===========================================================================
    FName C++ declarations exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2012 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if !ENUMS_ONLY
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#if !defined(__OLGAME_NAMES_H__) || defined(NAMES_ONLY)

#ifndef __OLGAME_NAMES_H__
#define __OLGAME_NAMES_H__
#endif

#ifndef AUTOGENERATE_NAME
#define DEFINED_NAME_MACRO
#define AUTOGENERATE_NAME(name) extern FName OLGAME_##name;
#endif


AUTOGENERATE_NAME(AddBot)
AUTOGENERATE_NAME(ApplyModifiers)
AUTOGENERATE_NAME(BashDoor)
AUTOGENERATE_NAME(BashDoorNotify)
AUTOGENERATE_NAME(BreakDoor)
AUTOGENERATE_NAME(BreakDoorNotify)
AUTOGENERATE_NAME(CanAnyoneSeeTarget)
AUTOGENERATE_NAME(CanUnpauseInPauseMenu)
AUTOGENERATE_NAME(CheckForProfileUpdate)
AUTOGENERATE_NAME(CheckpointIsEmpty)
AUTOGENERATE_NAME(ChooseClosestPatrolWaypoint)
AUTOGENERATE_NAME(ChooseNextPatrolWaypoint)
AUTOGENERATE_NAME(ClearCurrentMove)
AUTOGENERATE_NAME(ClearDisturbance)
AUTOGENERATE_NAME(ClosePauseMenu)
AUTOGENERATE_NAME(CompareMoves)
AUTOGENERATE_NAME(Condition)
AUTOGENERATE_NAME(DamageTarget)
AUTOGENERATE_NAME(DamageTargetRangeStartNotify)
AUTOGENERATE_NAME(DamageTargetRangeTickNotify)
AUTOGENERATE_NAME(DidAnyoneSeePlayerInBed)
AUTOGENERATE_NAME(DidAnyoneSeePlayerinLocker)
AUTOGENERATE_NAME(DingoUserInitializedCallback)
AUTOGENERATE_NAME(FindPlayer)
AUTOGENERATE_NAME(FinishedSaveDataDialog)
AUTOGENERATE_NAME(ForcePause)
AUTOGENERATE_NAME(FullScreenOverlayChanged)
AUTOGENERATE_NAME(HideMessage)
AUTOGENERATE_NAME(HideObjective)
AUTOGENERATE_NAME(HideSubtitle)
AUTOGENERATE_NAME(HideWeapon)
AUTOGENERATE_NAME(HideWeaponMatinee)
AUTOGENERATE_NAME(IgnoreTarget)
AUTOGENERATE_NAME(IsAMenuOpen)
AUTOGENERATE_NAME(IsInCreditsMenu)
AUTOGENERATE_NAME(IsInPauseMenu)
AUTOGENERATE_NAME(IsMainMenuOpen)
AUTOGENERATE_NAME(IsOnMainMenuScreen)
AUTOGENERATE_NAME(KnockbackStartNotify)
AUTOGENERATE_NAME(KnockbackTickNotify)
AUTOGENERATE_NAME(MoveThruBashable)
AUTOGENERATE_NAME(MoveThruDoor)
AUTOGENERATE_NAME(MoveThruLedge)
AUTOGENERATE_NAME(NotifyDummyGrab)
AUTOGENERATE_NAME(NotifyEnemyDoorBash)
AUTOGENERATE_NAME(NotifyEnemyDoorBreak)
AUTOGENERATE_NAME(NotifyEnemyDoorDone)
AUTOGENERATE_NAME(NotifyEnemyDoorOpen)
AUTOGENERATE_NAME(OnCheckpointReached)
AUTOGENERATE_NAME(OnCSAActivated)
AUTOGENERATE_NAME(OnDingoUserInitialized)
AUTOGENERATE_NAME(OnDoorKismetEvent)
AUTOGENERATE_NAME(OnItemConsumed)
AUTOGENERATE_NAME(OnKismetRemoteEvent)
AUTOGENERATE_NAME(OnLevelBecameVisible)
AUTOGENERATE_NAME(OnLocalDoorClose)
AUTOGENERATE_NAME(OnLocalDoorOpen)
AUTOGENERATE_NAME(OnPickupKismetEvent)
AUTOGENERATE_NAME(OnSetMesh)
AUTOGENERATE_NAME(OnTravelComplete)
AUTOGENERATE_NAME(PickBestTarget)
AUTOGENERATE_NAME(PickClosestInRange)
AUTOGENERATE_NAME(ProcessCheatInput)
AUTOGENERATE_NAME(PushNotify)
AUTOGENERATE_NAME(QueueAICommand)
AUTOGENERATE_NAME(Recalculate)
AUTOGENERATE_NAME(RemoveBot)
AUTOGENERATE_NAME(ResetAnimationMode)
AUTOGENERATE_NAME(RespawnHero)
AUTOGENERATE_NAME(RestartPlayer)
AUTOGENERATE_NAME(ReturnToPressStartMenu)
AUTOGENERATE_NAME(SaveDataDialogDoneCallback)
AUTOGENERATE_NAME(SaveProfile)
AUTOGENERATE_NAME(SetVisible)
AUTOGENERATE_NAME(ShouldBreak)
AUTOGENERATE_NAME(ShowingSubtitle)
AUTOGENERATE_NAME(ShowMenuType)
AUTOGENERATE_NAME(ShowMessage)
AUTOGENERATE_NAME(ShowObjective)
AUTOGENERATE_NAME(ShowSubtitle)
AUTOGENERATE_NAME(ShowWeapon)
AUTOGENERATE_NAME(ShowWeaponMatinee)
AUTOGENERATE_NAME(SimulateBackInput)
AUTOGENERATE_NAME(StartAnimating)
AUTOGENERATE_NAME(StartIdleSound)
AUTOGENERATE_NAME(StartMove)
AUTOGENERATE_NAME(StartNewGameAtCheckpoint)
AUTOGENERATE_NAME(StartScare)
AUTOGENERATE_NAME(StartWaitForDoor)
AUTOGENERATE_NAME(StopIdleSound)
AUTOGENERATE_NAME(StopPatrol)
AUTOGENERATE_NAME(StopScare)
AUTOGENERATE_NAME(ToggleAIAttackOnProximity)
AUTOGENERATE_NAME(ToggleAIIgnorePlayer)
AUTOGENERATE_NAME(TravelToStartupMap)
AUTOGENERATE_NAME(TriggerAudioDisturbance)
AUTOGENERATE_NAME(TriggerDisturbed)
AUTOGENERATE_NAME(TriggerVisualDisturbance)
AUTOGENERATE_NAME(TurnTo)
AUTOGENERATE_NAME(UnBindNoSave)
AUTOGENERATE_NAME(UnlockAchievement)
AUTOGENERATE_NAME(UpdateLocalCacheOfProfileSettings)

#ifdef DEFINED_NAME_MACRO
#undef DEFINED_NAME_MACRO
#undef AUTOGENERATE_NAME
#endif

#endif	//HEADER_GUARD

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#endif	//	!ENUMS_ONLY

