/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2012 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "OLGameNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_OLGAME_SEQUENCE_ENUMS
#define INCLUDED_OLGAME_SEQUENCE_ENUMS 1

enum EHobbleIntensity
{
    HI_VeryBad              =0,
    HI_Bad                  =1,
    HI_NotSoBad             =2,
    HI_RatherOk             =3,
    HI_Healed               =4,
    HI_MAX                  =5,
};
#define FOREACH_ENUM_EHOBBLEINTENSITY(op) \
    op(HI_VeryBad) \
    op(HI_Bad) \
    op(HI_NotSoBad) \
    op(HI_RatherOk) \
    op(HI_Healed) 
enum MovieEffectAnim
{
    MEA_Random              =0,
    MEA_Anim1               =1,
    MEA_Anim2               =2,
    MEA_Anim3               =3,
    MEA_MAX                 =4,
};
#define FOREACH_ENUM_MOVIEEFFECTANIM(op) \
    op(MEA_Random) \
    op(MEA_Anim1) \
    op(MEA_Anim2) \
    op(MEA_Anim3) 
enum ENVEvent
{
    NVE_CamcorderActivated  =0,
    NVE_CamcorderDeactivated=1,
    NVE_DefaultViewSelected =2,
    NVE_PassiveNVSelected   =3,
    NVE_ActiveNVSelected    =4,
    NVE_OutOfBatteries      =5,
    NVE_MAX                 =6,
};
#define FOREACH_ENUM_ENVEVENT(op) \
    op(NVE_CamcorderActivated) \
    op(NVE_CamcorderDeactivated) \
    op(NVE_DefaultViewSelected) \
    op(NVE_PassiveNVSelected) \
    op(NVE_ActiveNVSelected) \
    op(NVE_OutOfBatteries) 

#endif // !INCLUDED_OLGAME_SEQUENCE_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_OLGAME_SEQUENCE_CLASSES
#define INCLUDED_OLGAME_SEQUENCE_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class UOLSeqAct_Achievement : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Achievement
    MS_ALIGN(4) BYTE achievement GCC_ALIGN(4); // Extra alignment flags needed because all properties are bytes
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_Achievement

    DECLARE_CLASS(UOLSeqAct_Achievement,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_AdjustToFloor : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_AdjustToFloor
    FLOAT Duration;
    FLOAT HeightOffset;
    //## END PROPS OLSeqAct_AdjustToFloor

    DECLARE_CLASS(UOLSeqAct_AdjustToFloor,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_AIAbortPatrol : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_AIAbortPatrol
    //## END PROPS OLSeqAct_AIAbortPatrol

    DECLARE_CLASS(UOLSeqAct_AIAbortPatrol,USequenceAction,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqAct_AIAbortPatrol)
};

class UOLSeqAct_AIStartPatrol : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_AIStartPatrol
    class ARoute* PatrolRoute;
    BITFIELD bStartAtClosestPoint:1;
    BITFIELD FollowPlayer:1;
    SCRIPT_ALIGN;
    BYTE PatrolMode;
    FLOAT FollowDistance;
    FLOAT FollowUpdateRate;
    //## END PROPS OLSeqAct_AIStartPatrol

    DECLARE_CLASS(UOLSeqAct_AIStartPatrol,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
	virtual void  Activated();
};

struct FAnimParams
{
    FName AnimName;
    BITFIELD bLooping:1;
    FLOAT BlendInTime;
    FLOAT BlendOutTime;

    /** Constructors */
    FAnimParams() {}
    FAnimParams(EEventParm)
    {
        appMemzero(this, sizeof(FAnimParams));
    }
};

class UOLSeqAct_AnimControl : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_AnimControl
    FName BaseAnimName;
    TArrayNoInit<struct FAnimParams> ExtraAnims;
    FName SlotName;
    FName BaseAnimNodeName;
    INT PlayingIdx;
    //## END PROPS OLSeqAct_AnimControl

    DECLARE_CLASS(UOLSeqAct_AnimControl,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
	virtual void DeActivated() {}

	void StartBaseAnim(ASkeletalMeshActor* sma);
	void StartNewAnim(ASkeletalMeshActor* sma, const FAnimParams& params);

	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

private:
	void CheckAnimEnd();
};

class UOLSeqAct_Blur : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Blur
    FLOAT Amount;
    FLOAT Duration;
    FLOAT BlendInTime;
    FLOAT BlendOutTime;
    FLOAT Desaturation;
    //## END PROPS OLSeqAct_Blur

    DECLARE_CLASS(UOLSeqAct_Blur,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_Camcorder : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Camcorder
    BITFIELD bWithNightVision:1;
    FLOAT NewMinFOV;
    INT NewNumBatteries;
    FLOAT NewCurrentEnergy;
    //## END PROPS OLSeqAct_Camcorder

    DECLARE_CLASS(UOLSeqAct_Camcorder,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_CameraGlitch : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_CameraGlitch
    FLOAT GlitchDuration;
    FLOAT GlitchIntensity;
    FLOAT GlitchFrequency;
    //## END PROPS OLSeqAct_CameraGlitch

    DECLARE_CLASS(UOLSeqAct_CameraGlitch,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_CameraParticleEffect : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_CameraParticleEffect
    class UParticleSystem* ParticleSystemTemplate;
    FLOAT Duration;
    FLOAT PlaneDist;
    //## END PROPS OLSeqAct_CameraParticleEffect

    DECLARE_CLASS(UOLSeqAct_CameraParticleEffect,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_CameraShake : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_CameraShake
    struct FCameraShakeData Params;
    //## END PROPS OLSeqAct_CameraShake

    DECLARE_CLASS(UOLSeqAct_CameraShake,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_ChokePoint : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_ChokePoint
    BITFIELD bWaitingForLoaded:1;
    BITFIELD bWaitingForVisible:1;
    BITFIELD bNonBlocking:1;
    TArrayNoInit<FName> LevelNames;
    //## END PROPS OLSeqAct_ChokePoint

    DECLARE_CLASS(UOLSeqAct_ChokePoint,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);

	UBOOL IsLoadingComplete();
};

class UOLSeqAct_ConditionalHideBatteries : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_ConditionalHideBatteries
    INT MaxNumBatteries;
    BITFIELD bHideInHardMode:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_ConditionalHideBatteries

    DECLARE_CLASS(UOLSeqAct_ConditionalHideBatteries,USequenceAction,0,OLGame)
	void Activated();
};

class UOLSeqAct_CrackCameraGlass : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_CrackCameraGlass
    //## END PROPS OLSeqAct_CrackCameraGlass

    DECLARE_CLASS(UOLSeqAct_CrackCameraGlass,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_DarkLightControl : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_DarkLightControl
    FLOAT DarkLightBrightness;
    FLOAT DarkLightRadius;
    //## END PROPS OLSeqAct_DarkLightControl

    DECLARE_CLASS(UOLSeqAct_DarkLightControl,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_Door : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Door
    FLOAT RotationSpeedOverride;
    FLOAT OpenAngle;
    BITFIELD bNoSound:1;
    BITFIELD bBashReversed:1;
    BITFIELD bSwitchToBreakingMesh:1;
    SCRIPT_ALIGN;
    struct FDoorShakeData ShakeParams;
    BYTE CancelBashDirection;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_Door

    DECLARE_CLASS(UOLSeqAct_Door,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_DoorStatus : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_DoorStatus
    FLOAT OpenAngle;
    //## END PROPS OLSeqAct_DoorStatus

    DECLARE_CLASS(UOLSeqAct_DoorStatus,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_Fade : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Fade
    BITFIELD bFadeIn:1;
    BITFIELD bForceStartValue:1;
    FLOAT Opacity;
    FColor FadeColor;
    FLOAT Duration;
    //## END PROPS OLSeqAct_Fade

    DECLARE_CLASS(UOLSeqAct_Fade,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_ForceStance : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_ForceStance
    BITFIELD bCrouch:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_ForceStance

    DECLARE_CLASS(UOLSeqAct_ForceStance,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_GameOver : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_GameOver
    //## END PROPS OLSeqAct_GameOver

    DECLARE_CLASS(UOLSeqAct_GameOver,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_GameplayItem : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_GameplayItem
    FName ItemName;
    //## END PROPS OLSeqAct_GameplayItem

    DECLARE_CLASS(UOLSeqAct_GameplayItem,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_HeroControl : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_HeroControl
    FLOAT FixedDuration;
    FLOAT LookAtBlendInTime;
    FLOAT MovementSpeed;
    FLOAT RotationSpeed;
    class AActor* GoToTarget;
    class AActor* LookAtTarget;
    BITFIELD bCompleted:1;
    BITFIELD bPendingKill:1;
    FLOAT ElapsedTime;
    FLOAT Duration;
    FVector OriginalCamLocation;
    FRotator OriginalCamRotation;
    //## END PROPS OLSeqAct_HeroControl

    DECLARE_CLASS(UOLSeqAct_HeroControl,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
	virtual void Activated();
};

class UOLSeqAct_IgnoreBaseRotation : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_IgnoreBaseRotation
    //## END PROPS OLSeqAct_IgnoreBaseRotation

    DECLARE_CLASS(UOLSeqAct_IgnoreBaseRotation,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_Limp : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Limp
    MS_ALIGN(4) BYTE HobbleIntensity GCC_ALIGN(4); // Extra alignment flags needed because all properties are bytes
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_Limp

    DECLARE_CLASS(UOLSeqAct_Limp,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_LoadingScreen : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_LoadingScreen
    //## END PROPS OLSeqAct_LoadingScreen

    DECLARE_CLASS(UOLSeqAct_LoadingScreen,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_MonitorPlayerSpeed : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_MonitorPlayerSpeed
    FLOAT MaxSpeedForIdle;
    FLOAT MaxSpeedForWalk;
    FLOAT MaxSpeedForRun;
    FLOAT SpecificThreshold;
    BITFIELD bRunning:1;
    BITFIELD bBelowThreshold:1;
    INT CurrentStateIdx;
    FLOAT LastEventTime;
    //## END PROPS OLSeqAct_MonitorPlayerSpeed

    DECLARE_CLASS(UOLSeqAct_MonitorPlayerSpeed,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
	virtual void DeActivated() {}
};

class UOLSeqAct_MovieEffect : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_MovieEffect
    FLOAT ScaleIntensity;
    BITFIELD bStartAtRandomFrame:1;
    class UTextureMovie* Movie;
    class UAkEvent* SndEventPlay;
    class UAkEvent* SndEventStop;
    BYTE AnimType;
    TArrayNoInit<FVector2D> Anim1;
    TArrayNoInit<FVector2D> Anim2;
    TArrayNoInit<FVector2D> Anim3;
    //## END PROPS OLSeqAct_MovieEffect

    DECLARE_CLASS(UOLSeqAct_MovieEffect,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_NightVisionStatus : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_NightVisionStatus
    FLOAT RemainingBatteries;
    //## END PROPS OLSeqAct_NightVisionStatus

    DECLARE_CLASS(UOLSeqAct_NightVisionStatus,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_OpenMainMenu : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_OpenMainMenu
    //## END PROPS OLSeqAct_OpenMainMenu

    DECLARE_CLASS(UOLSeqAct_OpenMainMenu,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_Pushable : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_Pushable
    //## END PROPS OLSeqAct_Pushable

    DECLARE_CLASS(UOLSeqAct_Pushable,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_PushableObject : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_PushableObject
    //## END PROPS OLSeqAct_PushableObject

    DECLARE_CLASS(UOLSeqAct_PushableObject,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_RainEffect : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_RainEffect
    //## END PROPS OLSeqAct_RainEffect

    DECLARE_CLASS(UOLSeqAct_RainEffect,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_ReadDocument : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_ReadDocument
    FName DocumentName;
    //## END PROPS OLSeqAct_ReadDocument

    DECLARE_CLASS(UOLSeqAct_ReadDocument,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_SetEnemyMoveSpeed : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_SetEnemyMoveSpeed
    BYTE MoveSpeedMode;
    FLOAT PatrolSpeedOverride;
    FLOAT InvestigateSpeedOverride;
    FLOAT ChaseSpeedOverride;
    FLOAT AccelRate;
    FLOAT DecelRate;
    FLOAT SpeedNoVisibility;
    FLOAT ChaseSpeedAtMinDist;
    FLOAT ChaseSpeedAtMaxDist;
    FLOAT ChaseDistMin;
    FLOAT ChaseDistMax;
    //## END PROPS OLSeqAct_SetEnemyMoveSpeed

    DECLARE_CLASS(UOLSeqAct_SetEnemyMoveSpeed,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_SetObjective : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_SetObjective
    FName ObjectiveTextId;
    BITFIELD bActivateOnlyOnce:1;
    BITFIELD bResetOnPlayerDeath:1;
    BITFIELD bHasBeenActivated:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_SetObjective

    DECLARE_CLASS(UOLSeqAct_SetObjective,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_SetPlayerSpeed : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_SetPlayerSpeed
    FLOAT TargetSpeed;
    //## END PROPS OLSeqAct_SetPlayerSpeed

    DECLARE_CLASS(UOLSeqAct_SetPlayerSpeed,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_SetPlayerWalkingStyle : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_SetPlayerWalkingStyle
    BYTE WalkingStyle;
    FLOAT WalkSpeedOverride;
    FLOAT RunSpeedOverride;
    FLOAT AccelApproachFactorOverride;
    FLOAT DecelApproachFactorOverride;
    //## END PROPS OLSeqAct_SetPlayerWalkingStyle

    DECLARE_CLASS(UOLSeqAct_SetPlayerWalkingStyle,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_SplashScreen : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_SplashScreen
    BITFIELD bPauseGame:1;
    BITFIELD bAlwaysReady:1;
    BITFIELD bDone:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_SplashScreen

    DECLARE_CLASS(UOLSeqAct_SplashScreen,USeqAct_Latent,0,OLGame)
	virtual void Activated();
	virtual UBOOL UpdateOp(FLOAT deltaTime);

	void Continue();
};

class UOLSeqAct_StopCameraShake : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_StopCameraShake
    //## END PROPS OLSeqAct_StopCameraShake

    DECLARE_CLASS(UOLSeqAct_StopCameraShake,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqAct_Struggle : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_Struggle
    struct FStruggleConfig Config;
    class ASkeletalMeshActor* Enemy;
    FVector RefLocation;
    FVector RefDirection;
    BITFIELD bSucceeded:1;
    BITFIELD bFailed:1;
    BITFIELD bObserverOnly:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqAct_Struggle

    DECLARE_CLASS(UOLSeqAct_Struggle,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
	virtual void DeActivated() {}

	void Init();
	void Start();
};

class UOLSeqAct_ToggleNightVision : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_ToggleNightVision
    //## END PROPS OLSeqAct_ToggleNightVision

    DECLARE_CLASS(UOLSeqAct_ToggleNightVision,USequenceAction,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_Tutorial : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_Tutorial
    FName TutorialTextId;
    FName TutorialTextIdGamepad;
    FLOAT DisplayTime;
    INT TutorialId;
    BITFIELD bIsDone:1;
    FLOAT ElapsedTime;
    //## END PROPS OLSeqAct_Tutorial

    DECLARE_CLASS(UOLSeqAct_Tutorial,USeqAct_Latent,0,OLGame)
	virtual void Activated();
	virtual UBOOL UpdateOp(FLOAT deltaTime);
};

class UOLSeqAct_WaitForPlayerInput : public USeqAct_Latent
{
public:
    //## BEGIN PROPS OLSeqAct_WaitForPlayerInput
    BITFIELD bOnClick:1;
    BITFIELD bOnPrototypeActionA:1;
    BITFIELD bOnPrototypeActionB:1;
    BITFIELD bOnPrototypeActionC:1;
    BITFIELD bOnPrototypeActionD:1;
    BITFIELD bOnPrototypeActionE:1;
    BITFIELD bWaiting:1;
    FName PromptTextId;
    FLOAT MaxTime;
    FStringNoInit TranslatedPrompt;
    FLOAT StartedTime;
    //## END PROPS OLSeqAct_WaitForPlayerInput

    DECLARE_CLASS(UOLSeqAct_WaitForPlayerInput,USeqAct_Latent,0,OLGame)
	virtual UBOOL UpdateOp(FLOAT deltaTime);	
	virtual void DeActivated() {}
};

class UOLSeqAct_ZoomImpulse : public USequenceAction
{
public:
    //## BEGIN PROPS OLSeqAct_ZoomImpulse
    FLOAT ImpulseScale;
    //## END PROPS OLSeqAct_ZoomImpulse

    DECLARE_CLASS(UOLSeqAct_ZoomImpulse,USequenceAction,0,OLGame)
	virtual void Activated();
};

class UOLSeqCond_AIState : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_AIState
    //## END PROPS OLSeqCond_AIState

    DECLARE_CLASS(UOLSeqCond_AIState,USequenceCondition,0,OLGame)
	void Activated();
};

class UOLSeqCond_Checkpoint : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_Checkpoint
    FName CheckpointName;
    BITFIELD bStatusIsOk:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqCond_Checkpoint

    DECLARE_CLASS(UOLSeqCond_Checkpoint,USequenceCondition,0,OLGame)
public:
	void Activated();
	virtual void UpdateStatus();
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

#if WITH_EDITOR	
	virtual void DrawExtraInfo(FCanvas* Canvas, const FVector& BoxCenter);
protected:
	FString GetDisplayTitle() const;
#endif
};

class UOLSeqCond_CompareDeaths : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_CompareDeaths
    INT Value;
    //## END PROPS OLSeqCond_CompareDeaths

    DECLARE_CLASS(UOLSeqCond_CompareDeaths,USequenceCondition,0,OLGame)
	void Activated();
};

class UOLSeqCond_DetailMode : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_DetailMode
    BITFIELD bResult:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqCond_DetailMode

    DECLARE_CLASS(UOLSeqCond_DetailMode,USequenceCondition,0,OLGame)
	void Activated();
};

class UOLSeqCond_GameState : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_GameState
    FName GameStateName;
    BITFIELD bStatusIsOk:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqCond_GameState

    DECLARE_CLASS(UOLSeqCond_GameState,USequenceCondition,0,OLGame)
public:
	void Activated();
	virtual void UpdateStatus();
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

#if WITH_EDITOR	
	virtual void DrawExtraInfo(FCanvas* Canvas, const FVector& BoxCenter);
protected:
	FString GetDisplayTitle() const;
#endif
};

class UOLSeqCond_IsDemo : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_IsDemo
    BITFIELD bResult:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqCond_IsDemo

    DECLARE_CLASS(UOLSeqCond_IsDemo,USequenceCondition,0,OLGame)
	void Activated();
};

class UOLSeqCond_IsTouching : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_IsTouching
    BITFIELD bResult:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqCond_IsTouching

    DECLARE_CLASS(UOLSeqCond_IsTouching,USequenceCondition,0,OLGame)
	void Activated();
};

class UOLSeqCond_PlayerSpeed : public USequenceCondition
{
public:
    //## BEGIN PROPS OLSeqCond_PlayerSpeed
    FLOAT MaxSpeedForIdle;
    FLOAT MaxSpeedForWalk;
    FLOAT MaxSpeedForRun;
    FLOAT SpecificThreshold;
    BITFIELD bResult:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqCond_PlayerSpeed

    DECLARE_CLASS(UOLSeqCond_PlayerSpeed,USequenceCondition,0,OLGame)
	void Activated();
};

class UOLSeqEvent_AILostTarget : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_AILostTarget
    BITFIELD bOnlyAfterChase:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqEvent_AILostTarget

    DECLARE_CLASS(UOLSeqEvent_AILostTarget,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_AILostTarget)
};

class UOLSeqEvent_AIWaypointAction : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_AIWaypointAction
    //## END PROPS OLSeqEvent_AIWaypointAction

    DECLARE_CLASS(UOLSeqEvent_AIWaypointAction,USequenceEvent,0,OLGame)
	virtual UBOOL CheckActivate(AActor *InOriginator, AActor *InInstigator, UBOOL bTest=FALSE, TArray<INT>* ActivateIndices = NULL, UBOOL bPushTop = FALSE);	
};

class UOLSeqEvent_ApplyCheckpointState : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_ApplyCheckpointState
    FName CheckpointName;
    BITFIELD bStatusIsOk:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqEvent_ApplyCheckpointState

    DECLARE_CLASS(UOLSeqEvent_ApplyCheckpointState,USequenceEvent,0,OLGame)
public:
	virtual void UpdateStatus();
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

#if WITH_EDITOR	
	virtual void DrawExtraInfo(FCanvas* Canvas, const FVector& BoxCenter);
protected:
	FString GetDisplayTitle() const;
#endif
};

class UOLSeqEvent_ApplyGameState : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_ApplyGameState
    FName GameStateName;
    BITFIELD bStatusIsOk:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqEvent_ApplyGameState

    DECLARE_CLASS(UOLSeqEvent_ApplyGameState,USequenceEvent,0,OLGame)
public:
	virtual void UpdateStatus();
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

#if WITH_EDITOR	
	virtual void DrawExtraInfo(FCanvas* Canvas, const FVector& BoxCenter);
protected:
	FString GetDisplayTitle() const;
#endif
};

class UOLSeqEvent_BehaviorEvent : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_BehaviorEvent
    FName EventName;
    //## END PROPS OLSeqEvent_BehaviorEvent

    DECLARE_CLASS(UOLSeqEvent_BehaviorEvent,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_BehaviorEvent)
};

class UOLSeqEvent_CSAActivated : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_CSAActivated
    //## END PROPS OLSeqEvent_CSAActivated

    DECLARE_CLASS(UOLSeqEvent_CSAActivated,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_CSAActivated)
};

class UOLSeqEvent_Door : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_Door
    FLOAT OpenThreshold;
    BITFIELD bOpenThresholdOnlyForInteractiveOpen:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqEvent_Door

    DECLARE_CLASS(UOLSeqEvent_Door,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_Door)
};

class UOLSeqEvent_NightVision : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_NightVision
    //## END PROPS OLSeqEvent_NightVision

    DECLARE_CLASS(UOLSeqEvent_NightVision,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_NightVision)
};

class UOLSeqEvent_Pickup : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_Pickup
    //## END PROPS OLSeqEvent_Pickup

    DECLARE_CLASS(UOLSeqEvent_Pickup,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_Pickup)
};

class UOLSeqEvent_Pushable : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_Pushable
    //## END PROPS OLSeqEvent_Pushable

    DECLARE_CLASS(UOLSeqEvent_Pushable,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_Pushable)
};

class UOLSeqEvent_RecordingComplete : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_RecordingComplete
    //## END PROPS OLSeqEvent_RecordingComplete

    DECLARE_CLASS(UOLSeqEvent_RecordingComplete,USequenceEvent,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLSeqEvent_RecordingComplete)
};

class UOLSeqEvent_SpawnedAtCheckpoint : public USequenceEvent
{
public:
    //## BEGIN PROPS OLSeqEvent_SpawnedAtCheckpoint
    FName CheckpointName;
    BITFIELD bStatusIsOk:1;
    SCRIPT_ALIGN;
    //## END PROPS OLSeqEvent_SpawnedAtCheckpoint

    DECLARE_CLASS(UOLSeqEvent_SpawnedAtCheckpoint,USequenceEvent,0,OLGame)
public:
	virtual void UpdateStatus();
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

#if WITH_EDITOR	
	virtual void DrawExtraInfo(FCanvas* Canvas, const FVector& BoxCenter);
protected:
	FString GetDisplayTitle() const;
#endif
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_OLGAME_SEQUENCE_CLASSES
#endif // !NAMES_ONLY


#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef OLGAME_SEQUENCE_NATIVE_DEFS
#define OLGAME_SEQUENCE_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_OLGAME_SEQUENCE \
	UOLSeqAct_Achievement::StaticClass(); \
	UOLSeqAct_AdjustToFloor::StaticClass(); \
	UOLSeqAct_AIAbortPatrol::StaticClass(); \
	UOLSeqAct_AIStartPatrol::StaticClass(); \
	UOLSeqAct_AnimControl::StaticClass(); \
	UOLSeqAct_Blur::StaticClass(); \
	UOLSeqAct_Camcorder::StaticClass(); \
	UOLSeqAct_CameraGlitch::StaticClass(); \
	UOLSeqAct_CameraParticleEffect::StaticClass(); \
	UOLSeqAct_CameraShake::StaticClass(); \
	UOLSeqAct_ChokePoint::StaticClass(); \
	UOLSeqAct_ConditionalHideBatteries::StaticClass(); \
	UOLSeqAct_CrackCameraGlass::StaticClass(); \
	UOLSeqAct_DarkLightControl::StaticClass(); \
	UOLSeqAct_Door::StaticClass(); \
	UOLSeqAct_DoorStatus::StaticClass(); \
	UOLSeqAct_Fade::StaticClass(); \
	UOLSeqAct_ForceStance::StaticClass(); \
	UOLSeqAct_GameOver::StaticClass(); \
	UOLSeqAct_GameplayItem::StaticClass(); \
	UOLSeqAct_HeroControl::StaticClass(); \
	UOLSeqAct_IgnoreBaseRotation::StaticClass(); \
	UOLSeqAct_Limp::StaticClass(); \
	UOLSeqAct_LoadingScreen::StaticClass(); \
	UOLSeqAct_MonitorPlayerSpeed::StaticClass(); \
	UOLSeqAct_MovieEffect::StaticClass(); \
	UOLSeqAct_NightVisionStatus::StaticClass(); \
	UOLSeqAct_OpenMainMenu::StaticClass(); \
	UOLSeqAct_Pushable::StaticClass(); \
	UOLSeqAct_PushableObject::StaticClass(); \
	UOLSeqAct_RainEffect::StaticClass(); \
	UOLSeqAct_ReadDocument::StaticClass(); \
	UOLSeqAct_SetEnemyMoveSpeed::StaticClass(); \
	UOLSeqAct_SetObjective::StaticClass(); \
	UOLSeqAct_SetPlayerSpeed::StaticClass(); \
	UOLSeqAct_SetPlayerWalkingStyle::StaticClass(); \
	UOLSeqAct_SplashScreen::StaticClass(); \
	UOLSeqAct_StopCameraShake::StaticClass(); \
	UOLSeqAct_Struggle::StaticClass(); \
	UOLSeqAct_ToggleNightVision::StaticClass(); \
	UOLSeqAct_Tutorial::StaticClass(); \
	UOLSeqAct_WaitForPlayerInput::StaticClass(); \
	UOLSeqAct_ZoomImpulse::StaticClass(); \
	UOLSeqCond_AIState::StaticClass(); \
	UOLSeqCond_Checkpoint::StaticClass(); \
	UOLSeqCond_CompareDeaths::StaticClass(); \
	UOLSeqCond_DetailMode::StaticClass(); \
	UOLSeqCond_GameState::StaticClass(); \
	UOLSeqCond_IsDemo::StaticClass(); \
	UOLSeqCond_IsTouching::StaticClass(); \
	UOLSeqCond_PlayerSpeed::StaticClass(); \
	UOLSeqEvent_AILostTarget::StaticClass(); \
	UOLSeqEvent_AIWaypointAction::StaticClass(); \
	UOLSeqEvent_ApplyCheckpointState::StaticClass(); \
	UOLSeqEvent_ApplyGameState::StaticClass(); \
	UOLSeqEvent_BehaviorEvent::StaticClass(); \
	UOLSeqEvent_CSAActivated::StaticClass(); \
	UOLSeqEvent_Door::StaticClass(); \
	UOLSeqEvent_NightVision::StaticClass(); \
	UOLSeqEvent_Pickup::StaticClass(); \
	UOLSeqEvent_Pushable::StaticClass(); \
	UOLSeqEvent_RecordingComplete::StaticClass(); \
	UOLSeqEvent_SpawnedAtCheckpoint::StaticClass(); \

#endif // OLGAME_SEQUENCE_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Achievement,OLSeqAct_Achievement,achievement)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Achievement)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_AdjustToFloor,OLSeqAct_AdjustToFloor,Duration)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_AdjustToFloor,OLSeqAct_AdjustToFloor,HeightOffset)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_AdjustToFloor)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_AIAbortPatrol)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_AIStartPatrol,OLSeqAct_AIStartPatrol,PatrolRoute)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_AIStartPatrol,OLSeqAct_AIStartPatrol,FollowUpdateRate)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_AIStartPatrol)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_AnimControl,OLSeqAct_AnimControl,BaseAnimName)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_AnimControl,OLSeqAct_AnimControl,PlayingIdx)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_AnimControl)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Blur,OLSeqAct_Blur,Amount)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Blur,OLSeqAct_Blur,Desaturation)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Blur)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Camcorder,OLSeqAct_Camcorder,NewMinFOV)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Camcorder,OLSeqAct_Camcorder,NewCurrentEnergy)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Camcorder)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_CameraGlitch,OLSeqAct_CameraGlitch,GlitchDuration)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_CameraGlitch,OLSeqAct_CameraGlitch,GlitchFrequency)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_CameraGlitch)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_CameraParticleEffect,OLSeqAct_CameraParticleEffect,ParticleSystemTemplate)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_CameraParticleEffect,OLSeqAct_CameraParticleEffect,PlaneDist)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_CameraParticleEffect)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_CameraShake,OLSeqAct_CameraShake,Params)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_CameraShake)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_ChokePoint,OLSeqAct_ChokePoint,LevelNames)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_ChokePoint)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_ConditionalHideBatteries,OLSeqAct_ConditionalHideBatteries,MaxNumBatteries)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_ConditionalHideBatteries)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_CrackCameraGlass)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_DarkLightControl,OLSeqAct_DarkLightControl,DarkLightBrightness)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_DarkLightControl,OLSeqAct_DarkLightControl,DarkLightRadius)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_DarkLightControl)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Door,OLSeqAct_Door,RotationSpeedOverride)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Door,OLSeqAct_Door,CancelBashDirection)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Door)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_DoorStatus,OLSeqAct_DoorStatus,OpenAngle)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_DoorStatus)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Fade,OLSeqAct_Fade,Opacity)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Fade,OLSeqAct_Fade,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Fade)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_ForceStance)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_GameOver)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_GameplayItem,OLSeqAct_GameplayItem,ItemName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_GameplayItem)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_HeroControl,OLSeqAct_HeroControl,FixedDuration)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_HeroControl,OLSeqAct_HeroControl,OriginalCamRotation)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_HeroControl)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_IgnoreBaseRotation)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Limp,OLSeqAct_Limp,HobbleIntensity)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Limp)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_LoadingScreen)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_MonitorPlayerSpeed,OLSeqAct_MonitorPlayerSpeed,MaxSpeedForIdle)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_MonitorPlayerSpeed,OLSeqAct_MonitorPlayerSpeed,LastEventTime)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_MonitorPlayerSpeed)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_MovieEffect,OLSeqAct_MovieEffect,ScaleIntensity)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_MovieEffect,OLSeqAct_MovieEffect,Anim3)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_MovieEffect)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_NightVisionStatus,OLSeqAct_NightVisionStatus,RemainingBatteries)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_NightVisionStatus)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_OpenMainMenu)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Pushable)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_PushableObject)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_RainEffect)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_ReadDocument,OLSeqAct_ReadDocument,DocumentName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_ReadDocument)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_SetEnemyMoveSpeed,OLSeqAct_SetEnemyMoveSpeed,MoveSpeedMode)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_SetEnemyMoveSpeed,OLSeqAct_SetEnemyMoveSpeed,ChaseDistMax)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_SetEnemyMoveSpeed)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_SetObjective,OLSeqAct_SetObjective,ObjectiveTextId)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_SetObjective)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_SetPlayerSpeed,OLSeqAct_SetPlayerSpeed,TargetSpeed)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_SetPlayerSpeed)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_SetPlayerWalkingStyle,OLSeqAct_SetPlayerWalkingStyle,WalkingStyle)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_SetPlayerWalkingStyle,OLSeqAct_SetPlayerWalkingStyle,DecelApproachFactorOverride)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_SetPlayerWalkingStyle)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_SplashScreen)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_StopCameraShake)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Struggle,OLSeqAct_Struggle,Config)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Struggle,OLSeqAct_Struggle,RefDirection)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Struggle)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_ToggleNightVision)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Tutorial,OLSeqAct_Tutorial,TutorialTextId)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_Tutorial,OLSeqAct_Tutorial,ElapsedTime)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_Tutorial)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_WaitForPlayerInput,OLSeqAct_WaitForPlayerInput,PromptTextId)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_WaitForPlayerInput,OLSeqAct_WaitForPlayerInput,StartedTime)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_WaitForPlayerInput)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqAct_ZoomImpulse,OLSeqAct_ZoomImpulse,ImpulseScale)
VERIFY_CLASS_SIZE_NODIE(UOLSeqAct_ZoomImpulse)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_AIState)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqCond_Checkpoint,OLSeqCond_Checkpoint,CheckpointName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_Checkpoint)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqCond_CompareDeaths,OLSeqCond_CompareDeaths,Value)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_CompareDeaths)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_DetailMode)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqCond_GameState,OLSeqCond_GameState,GameStateName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_GameState)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_IsDemo)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_IsTouching)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqCond_PlayerSpeed,OLSeqCond_PlayerSpeed,MaxSpeedForIdle)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqCond_PlayerSpeed,OLSeqCond_PlayerSpeed,SpecificThreshold)
VERIFY_CLASS_SIZE_NODIE(UOLSeqCond_PlayerSpeed)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_AILostTarget)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_AIWaypointAction)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqEvent_ApplyCheckpointState,OLSeqEvent_ApplyCheckpointState,CheckpointName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_ApplyCheckpointState)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqEvent_ApplyGameState,OLSeqEvent_ApplyGameState,GameStateName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_ApplyGameState)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqEvent_BehaviorEvent,OLSeqEvent_BehaviorEvent,EventName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_BehaviorEvent)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_CSAActivated)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqEvent_Door,OLSeqEvent_Door,OpenThreshold)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_Door)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_NightVision)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_Pickup)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_Pushable)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_RecordingComplete)
VERIFY_CLASS_OFFSET_NODIE(UOLSeqEvent_SpawnedAtCheckpoint,OLSeqEvent_SpawnedAtCheckpoint,CheckpointName)
VERIFY_CLASS_SIZE_NODIE(UOLSeqEvent_SpawnedAtCheckpoint)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
