/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2012 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "OLGameNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_OLGAME_ANIM_ENUMS
#define INCLUDED_OLGAME_ANIM_ENUMS 1

enum EStruggleAnimPhase
{
    SAP_StartIdle           =0,
    SAP_Entry               =1,
    SAP_Cycle               =2,
    SAP_Success             =3,
    SAP_Fail                =4,
    SAP_SuccessIdle         =5,
    SAP_MAX                 =6,
};
#define FOREACH_ENUM_ESTRUGGLEANIMPHASE(op) \
    op(SAP_StartIdle) \
    op(SAP_Entry) \
    op(SAP_Cycle) \
    op(SAP_Success) \
    op(SAP_Fail) \
    op(SAP_SuccessIdle) 
enum EDoorInteraction
{
    DI_Open                 =0,
    DI_Close                =1,
    DI_MAX                  =2,
};
#define FOREACH_ENUM_EDOORINTERACTION(op) \
    op(DI_Open) \
    op(DI_Close) 

#endif // !INCLUDED_OLGAME_ANIM_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_OLGAME_ANIM_CLASSES
#define INCLUDED_OLGAME_ANIM_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class UOLAnimBlendByEnemyEnvironment : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimBlendByEnemyEnvironment
    //## END PROPS OLAnimBlendByEnemyEnvironment

    DECLARE_CLASS(UOLAnimBlendByEnemyEnvironment,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimBlendByEnemyMode : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimBlendByEnemyMode
    //## END PROPS OLAnimBlendByEnemyMode

    DECLARE_CLASS(UOLAnimBlendByEnemyMode,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimBlendByHobblingIntensity : public UAnimNodeBlend
{
public:
    //## BEGIN PROPS OLAnimBlendByHobblingIntensity
    //## END PROPS OLAnimBlendByHobblingIntensity

    DECLARE_CLASS(UOLAnimBlendByHobblingIntensity,UAnimNodeBlend,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
};

class UOLAnimBlendByIdle : public UUDKAnimBlendBase
{
public:
    //## BEGIN PROPS OLAnimBlendByIdle
    FName ChildSynchGroup;
    //## END PROPS OLAnimBlendByIdle

    DECLARE_CLASS(UOLAnimBlendByIdle,UUDKAnimBlendBase,0,OLGame)
	virtual void OnBecomeRelevant();
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnChildAnimEnd(UAnimNodeSequence* Child, FLOAT PlayedTime, FLOAT ExcessTime);

private:
	enum { IdxIdle = 0, IdxMoving = 1, IdxStart = 2, IdxStop = 3 };

	void ResetSynchGroup();
};

class UOLAnimBlendByLeaning : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimBlendByLeaning
    FLOAT CurrentRatio;
    //## END PROPS OLAnimBlendByLeaning

    DECLARE_CLASS(UOLAnimBlendByLeaning,UAnimNodeBlendBase,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();

private:
	enum { IdxIdle = 0, IdxLeft = 1, IdxRight = 2 };
};

class UOLAnimBlendByLocomotionMode : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimBlendByLocomotionMode
    TArrayNoInit<FLOAT> ChildBlendTimes;
    //## END PROPS OLAnimBlendByLocomotionMode

    DECLARE_CLASS(UOLAnimBlendByLocomotionMode,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimBlendByPosture : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimBlendByPosture
    //## END PROPS OLAnimBlendByPosture

    DECLARE_CLASS(UOLAnimBlendByPosture,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimBlendBySpeed : public UAnimNodeBlend
{
public:
    //## BEGIN PROPS OLAnimBlendBySpeed
    FLOAT MinSpeed;
    FLOAT MaxSpeed;
    FLOAT MaxWeightRate;
    FLOAT CurrentWeight;
    //## END PROPS OLAnimBlendBySpeed

    DECLARE_CLASS(UOLAnimBlendBySpeed,UAnimNodeBlend,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimBlendBySpeedExpandable : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimBlendBySpeedExpandable
    TArrayNoInit<FLOAT> AnimSpeeds;
    BITFIELD bTimeScaleDown:1;
    BITFIELD bTimeScaleUp:1;
    FLOAT SmoothingCoefficient;
    FLOAT CurrentSpeed;
    FLOAT SliderPosition;
    //## END PROPS OLAnimBlendBySpeedExpandable

    DECLARE_CLASS(UOLAnimBlendBySpeedExpandable,UAnimNodeBlendBase,0,OLGame)
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent);

	virtual void InitAnim( USkeletalMeshComponent* meshComp, UAnimNodeBlendBase* Parent );
	virtual void ResetAnimNodeToSource(UAnimNode *SourceNode);
	virtual void TickAnim(FLOAT deltaTime);

	virtual void OnBecomeRelevant();
	
	// AnimTree editor interface
	virtual INT GetNumSliders() const { return 1; }
	virtual FLOAT GetSliderPosition(INT SliderIndex, INT ValueIndex);
	virtual void HandleSliderMove(INT SliderIndex, INT ValueIndex, FLOAT NewSliderValue);
	virtual FString GetSliderDrawValue(INT SliderIndex);

	// AnimNodeBlendBase interface
	virtual void OnAddChild(INT ChildNum);
	virtual void OnRemoveChild(INT ChildNum);

private:
	void SetWeightsFromSpeed(FLOAT Speed);
};

class UOLAnimBlendBySwarmForm : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimBlendBySwarmForm
    //## END PROPS OLAnimBlendBySwarmForm

    DECLARE_CLASS(UOLAnimBlendBySwarmForm,UAnimNodeBlendList,0,OLGame)
	enum { IdxSwarm = 0, IdxHuman = 1, IdxMorphingToSwarm = 2, IdxMorphingToHuman = 3 };
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimBlendDirectional : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimBlendDirectional
    BITFIELD bTimescaleDiagonals:1;
    BITFIELD bTimescaleBelowExpectedSpeed:1;
    BITFIELD bTimescaleAboveExpectedSpeed:1;
    BITFIELD bUseReversedSideForBackwards:1;
    BITFIELD bReversingBackward:1;
    FLOAT ExpectedPawnSpeed;
    FLOAT BlendInIdleMaxSpeedPct;
    FLOAT SliderDirAngle;
    //## END PROPS OLAnimBlendDirectional

    DECLARE_CLASS(UOLAnimBlendDirectional,UAnimNodeBlendBase,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
	
	virtual INT GetNumSliders() const { return 1; }
	virtual FLOAT GetSliderPosition(INT SliderIndex, INT ValueIndex);
	virtual void HandleSliderMove(INT SliderIndex, INT ValueIndex, FLOAT NewSliderValue);
	virtual FString GetSliderDrawValue(INT SliderIndex);

	/** Workaround because OnBecomeRelevant/bJustBecameRelevant can be called a frame late, with idle weight */
	void SetFullForwardWeight();

private:
	enum 
	{ 
		IdxForward			= 0, 
		IdxBackward			= 1, 
		IdxLeft				= 2, 
		IdxRight				= 3, 
		IdxIdle				= 4,  
		IdxReverseLeft		= 5,
		IdxReverseRight	= 6,
	};
};

class UOLAnimCameraSpace : public UAnimNodeBlendPerBone
{
public:
    //## BEGIN PROPS OLAnimCameraSpace
    class UAnimNodeSlot* ChildSlot;
    class UOLAnimCustomBlend* ChildBlend;
    INT CameraBoneIdx;
    TArrayNoInit<INT> StartBoneIndices;
    TArrayNoInit<INT> ParentChain;
    //## END PROPS OLAnimCameraSpace

    DECLARE_CLASS(UOLAnimCameraSpace,UAnimNodeBlendPerBone,0,OLGame)
	virtual void InitAnim(USkeletalMeshComponent* MeshComp, UAnimNodeBlendBase* Parent);
	virtual void TickAnim(FLOAT deltaTime);
	virtual void GetBoneAtoms(FBoneAtomArray& Atoms, const TArray<BYTE>& DesiredBones, FBoneAtom& RootMotionDelta, INT& bHasRootMotion, FCurveKeyArray& CurveKeys);	
	virtual void BuildWeightList();
};

class UOLAnimConstrainedMovement : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimConstrainedMovement
    BITFIELD bUpDown:1;
    BITFIELD bCompleteCyclesOnly:1;
    BITFIELD bNoAutomaticRootMotion:1;
    BITFIELD bAutomaticMotion:1;
    BITFIELD bNetControlled:1;
    FLOAT CurrentRatio;
    FLOAT SmoothedDelta;
    INT LastTargetIdx;
    FLOAT NetSmoothedDelta;
    //## END PROPS OLAnimConstrainedMovement

    DECLARE_CLASS(UOLAnimConstrainedMovement,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
	virtual void GetBoneAtoms(FBoneAtomArray& Atoms, const TArray<BYTE>& DesiredBones, FBoneAtom& RootMotionDelta, INT& bHasRootMotion, FCurveKeyArray& CurveKeys);
};

class UOLAnimCrouchedTurnOnSpot : public UAnimNodeBlend
{
public:
    //## BEGIN PROPS OLAnimCrouchedTurnOnSpot
    FLOAT BaseHeading;
    FLOAT LastHeading;
    FLOAT TurningVelocity;
    FLOAT HandUpWeight;
    BITFIELD bHandUp:1;
    FLOAT IKStrength;
    FVector IKPosition;
    FRotator IKRotationWS;
    FVector ActorSpaceIKOffset;
    FQuat ActorSpaceIKRotation;
    class UAkEvent* HandUpSound;
    class UAkEvent* HandDownSound;
    //## END PROPS OLAnimCrouchedTurnOnSpot

    DECLARE_CLASS(UOLAnimCrouchedTurnOnSpot,UAnimNodeBlend,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
	virtual void OnCeaseRelevant();
};

class UOLAnimCustomBlend : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimCustomBlend
    BITFIELD bActive:1;
    BITFIELD bBlendingOut:1;
    BITFIELD bKeepLastPose:1;
    BITFIELD bInhibitEndNotifies:1;
    FLOAT BlendOutTime;
    FLOAT PlaybackTime;
    FLOAT BlendWeights[3];
    FLOAT bEarlyAnimEndFired;
    FLOAT TimeRemaining;
    INT NumActiveAnims;
    //## END PROPS OLAnimCustomBlend

    virtual FLOAT PlayCustomBlendUC(FName AnimA,FName AnimB,FLOAT WeightA,FLOAT BlendIn,FLOAT BlendOut);
    DECLARE_FUNCTION(execPlayCustomBlendUC)
    {
        P_GET_NAME(AnimA);
        P_GET_NAME(AnimB);
        P_GET_FLOAT(WeightA);
        P_GET_FLOAT(BlendIn);
        P_GET_FLOAT(BlendOut);
        P_FINISH;
        *(FLOAT*)Result=this->PlayCustomBlendUC(AnimA,AnimB,WeightA,BlendIn,BlendOut);
    }
    DECLARE_CLASS(UOLAnimCustomBlend,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaSeconds);

	FLOAT PlaySingleAnim(FName animName, FLOAT blendInTime=0.0f, FLOAT blendOutTime=0.0f, FLOAT rate=1.0f, FLOAT startRatio=0.0f); 
	FLOAT PlayCustomBlend(FName animNameA, FName animNameB, FLOAT blendWeightA, FLOAT blendInTime=0.0f, FLOAT blendOutTime=0.0f, FLOAT rate=1.0f, FLOAT startRatio=0.0f);
	FLOAT PlayCustomBlend(FName animNameA, FName animNameB, FName animNameC, FLOAT blendWeightA, FLOAT blendWeightB, FLOAT blendInTime=0.0f, FLOAT blendOutTime=0.0f, FLOAT rate=1.0f, FLOAT startRatio=0.0f);
	FLOAT PlayBlendSpace(const FBlendSpaceNode nodes[], INT numNodes, const INT blendSpaces[][3], INT numSpaces, const FVector2D& coord, FLOAT blendInTime=0.0f, FLOAT blendOutTime=0.0f, FLOAT rate=1.0f, FLOAT startRatio=0.0f);
	void StartBlendingOut();
	void FinishPlaying();
	void StopTickingSequences();

	FBoneAtom GetTotalRootMotion() const;	
	FBoneAtom GetCameraFinalRelativePosition() const;	

private:
	FLOAT PlayCustomBlend_Internal(FName animNames[3], FLOAT blendInTime=0.0f, FLOAT blendOutTime=0.0f, FLOAT rate=1.0f, FLOAT startRatio=0.0f);
	UAnimNodeSequence* GetPrimaryNode() const;
};

struct FCycleBreaker
{
    FLOAT MinWeight;
    FLOAT MaxWeight;
    BITFIELD bPlayStartToEnd:1;
    FLOAT MinDuration;
    FLOAT MaxDuration;
    FLOAT MinRate;
    FLOAT MaxRate;
    FLOAT BlendInSpeed;
    FLOAT BlendOutSpeed;
    FLOAT Probability;
    FLOAT LayerProbability;
    TArrayNoInit<class UClass*> SpecificClasses;
    FLOAT CurrentWeight;
    FLOAT TargetWeight;

    /** Constructors */
    FCycleBreaker() {}
    FCycleBreaker(EEventParm)
    {
        appMemzero(this, sizeof(FCycleBreaker));
    }
};

class UOLAnimCycleBreaker : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimCycleBreaker
    FLOAT DefaultCycleBias;
    FLOAT DefaultStretchDuration;
    TArrayNoInit<struct FCycleBreaker> Breakers;
    struct FCycleBreaker BreakerTemplate;
    FLOAT NextBreakerWeightTransition;
    TArrayNoInit<INT> ValidBreakers;
    //## END PROPS OLAnimCycleBreaker

    DECLARE_CLASS(UOLAnimCycleBreaker,UAnimNodeBlendBase,0,OLGame)
	virtual void InitAnim(USkeletalMeshComponent* MeshComp, UAnimNodeBlendBase* Parent);
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();

	// AnimTree editor interface
	virtual INT GetNumSliders() const { return 1; }
	virtual FLOAT GetSliderPosition(INT SliderIndex, INT ValueIndex);
	virtual FString GetSliderDrawValue(INT SliderIndex);

	virtual void OnAddChild(INT newIdx);
	virtual void OnRemoveChild(INT remIdx);

private:
	void ActivateNewBreaker();
	void UpdateBreakers(FLOAT deltaTime);
	UAnimNodeSequence* GetAnimNodeForBreaker(INT breakerIdx);
};

class UOLAnimSmarterIdle : public UOLAnimCycleBreaker
{
public:
    //## BEGIN PROPS OLAnimSmarterIdle
    BITFIELD bModifyPlayrateIdle:1;
    FLOAT IdleMinRate;
    FLOAT IdleMaxRate;
    FLOAT IdleRateMinDuration;
    FLOAT IdleRateMaxDuration;
    FLOAT IdleRateTransitionSpeed;
    FLOAT CurrentIdleRate;
    FLOAT TargetIdleRate;
    FLOAT NextIdleRateTransition;
    //## END PROPS OLAnimSmarterIdle

    DECLARE_CLASS(UOLAnimSmarterIdle,UOLAnimCycleBreaker,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();

	virtual FString GetSliderDrawValue(INT SliderIndex);
};

class UOLAnimDoorInteraction : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimDoorInteraction
    FLOAT InitialRatio;
    FLOAT CurrentRatio;
    FLOAT SmoothedDelta;
    FLOAT PlayRate;
    FLOAT MaxRatio;
    //## END PROPS OLAnimDoorInteraction

    DECLARE_CLASS(UOLAnimDoorInteraction,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimEnemyStruggle : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimEnemyStruggle
    //## END PROPS OLAnimEnemyStruggle

    DECLARE_CLASS(UOLAnimEnemyStruggle,UAnimNodeBlendList,0,OLGame)
	virtual void OnBecomeRelevant();
	void SetPhase(EStruggleAnimPhase phase, const FStruggleConfig& cfg);
};

class UOLAnimHeatShielding : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimHeatShielding
    FLOAT MinimumDistance;
    FLOAT LowDistance;
    FLOAT HighDistance;
    BITFIELD bActive:1;
    FLOAT HeatShieldingWeight;
    FLOAT HeatStrength;
    //## END PROPS OLAnimHeatShielding

    DECLARE_CLASS(UOLAnimHeatShielding,UAnimNodeBlendBase,0,OLGame)
	virtual void TickAnim(FLOAT deltaSeconds);
	virtual void OnBecomeRelevant();

protected:
	void SetActive(UBOOL isActive);
};

class UOLAnimLocomotion : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimLocomotion
    FLOAT MinMovingContribUnder90;
    FLOAT MinMovingContribOver90;
    FLOAT BlendTimePct;
    INT ActiveChildIdx;
    FLOAT TransitionBlendTime;
    BITFIELD bIsTurning:1;
    BITFIELD bReachedHalfTurn:1;
    BITFIELD bMoveOnNextFrame:1;
    FLOAT SliderPosition;
    //## END PROPS OLAnimLocomotion

    DECLARE_CLASS(UOLAnimLocomotion,UAnimNodeBlendBase,0,OLGame)
	virtual void OnBecomeRelevant();
	virtual void TickAnim(FLOAT deltaTime);


	virtual INT GetNumSliders() const { return 1; }
	virtual FLOAT GetSliderPosition(INT SliderIndex, INT ValueIndex);
	virtual void HandleSliderMove(INT SliderIndex, INT ValueIndex, FLOAT NewSliderValue);
	virtual FString GetSliderDrawValue(INT SliderIndex);

	UBOOL IsIdle() const { return ActiveChildIdx == IdxIdle; }
	UBOOL IsStarting() const { return ActiveChildIdx == IdxStart; }
	UBOOL IsStopping() const { return ActiveChildIdx == IdxStop; }
	UBOOL IsTurning() const { return bIsTurning; }

private:
	enum 
	{ 
		IdxIdle		= 0, 
		IdxMoving	= 1, 
		IdxStart		= 2, 
		IdxStop		= 3, 
		IdxLeft90	= 4, 
		IdxRight90	= 5,  
		IdxLeft180	= 6, 
		IdxRight180 = 7,  
	};

	void ResetAllSynchGroups();
};

class UOLAnimMultiCycleConstrainedMovement : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimMultiCycleConstrainedMovement
    BITFIELD bUpDown:1;
    BITFIELD bCompleteCyclesOnly:1;
    BITFIELD bCommitMoves:1;
    BITFIELD bNetControlled:1;
    FLOAT SmoothedDelta;
    FLOAT CurrentRatio;
    INT CurrentIdx;
    FLOAT NetSmoothedDelta;
    //## END PROPS OLAnimMultiCycleConstrainedMovement

    DECLARE_CLASS(UOLAnimMultiCycleConstrainedMovement,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();

	UBOOL CloserToA() const; // returns whether A or B is the closer node
	FLOAT GetCurrentPositionRatio() const; // return the current ration of the root motion when between A and B
};

class UOLAnimNodeDelayed : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimNodeDelayed
    FLOAT TimeDelay;
    FLOAT BlendTime;
    FLOAT ElapsedTime;
    //## END PROPS OLAnimNodeDelayed

    DECLARE_CLASS(UOLAnimNodeDelayed,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimNodeSlot : public UAnimNodeSlot
{
public:
    //## BEGIN PROPS OLAnimNodeSlot
    //## END PROPS OLAnimNodeSlot

    DECLARE_CLASS(UOLAnimNodeSlot,UAnimNodeSlot,0,OLGame)
    NO_DEFAULT_CONSTRUCTOR(UOLAnimNodeSlot)
};

class UOLAnimNotify_AttachWeapon : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_AttachWeapon
    class USkeletalMesh* WeaponSkelMesh;
    FStringNoInit AttachBoneName;
    FLOAT Duration;
    //## END PROPS OLAnimNotify_AttachWeapon

    DECLARE_CLASS(UOLAnimNotify_AttachWeapon,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual void NotifyEnd( class UAnimNodeSequence* NodeSeq, FLOAT AnimCurrentTime );
	virtual FString GetEditorComment() { return TEXT("AttachWeapon"); }
	virtual void AnimNotifyEventChanged(class UAnimNodeSequence* NodeSeq, FAnimNotifyEvent* OwnerEvent);
};

class UOLAnimNotify_Blur : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_Blur
    FLOAT Amount;
    FLOAT Duration;
    FLOAT BlendInTime;
    FLOAT BlendOutTime;
    FLOAT Desaturation;
    //## END PROPS OLAnimNotify_Blur

    DECLARE_CLASS(UOLAnimNotify_Blur,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("Blur"); }
};

class UOLAnimNotify_Door : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_Door
    BYTE Interaction;
    FLOAT AngleWhenOpen;
    FLOAT Duration;
    //## END PROPS OLAnimNotify_Door

    DECLARE_CLASS(UOLAnimNotify_Door,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return Interaction == DI_Open ? TEXT("Open Door") : TEXT("Close Door"); }
	virtual void AnimNotifyEventChanged(class UAnimNodeSequence* NodeSeq, FAnimNotifyEvent* OwnerEvent);
};

class UOLAnimNotify_Fade : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_Fade
    BITFIELD bFadeIn:1;
    BITFIELD bForceStartValue:1;
    FLOAT Opacity;
    FColor FadeColor;
    FLOAT Duration;
    //## END PROPS OLAnimNotify_Fade

    DECLARE_CLASS(UOLAnimNotify_Fade,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("Fade"); }
};

class UOLAnimNotify_LeftHandIK : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_LeftHandIK
    BYTE TargetType;
    FLOAT FadeInTime;
    FLOAT FadeOutTime;
    FVector EffectorOffset;
    FLOAT Duration;
    //## END PROPS OLAnimNotify_LeftHandIK

    DECLARE_CLASS(UOLAnimNotify_LeftHandIK,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("LeftHandIK"); }
	virtual void AnimNotifyEventChanged(class UAnimNodeSequence* NodeSeq, FAnimNotifyEvent* OwnerEvent);
};

class UOLAnimNotify_ModifyPlayrate : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_ModifyPlayrate
    FLOAT NewRate;
    //## END PROPS OLAnimNotify_ModifyPlayrate

    DECLARE_CLASS(UOLAnimNotify_ModifyPlayrate,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("PlayRate"); }
};

class UOLAnimNotify_NonFatalDamage : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_NonFatalDamage
    INT DamageAmount;
    //## END PROPS OLAnimNotify_NonFatalDamage

    DECLARE_CLASS(UOLAnimNotify_NonFatalDamage,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("NonFatalDamage"); }
};

class UOLAnimNotify_OverrideCameraParams : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_OverrideCameraParams
    BITFIELD bResetToDefault:1;
    BITFIELD bLocalSpacePlayerControl:1;
    BITFIELD bMinYaw:1;
    BITFIELD bMaxYaw:1;
    BITFIELD bMinPitchWS:1;
    BITFIELD bMaxPitchWS:1;
    BITFIELD bMinPitchCS:1;
    BITFIELD bMaxPitchCS:1;
    FLOAT MinYaw;
    FLOAT MaxYaw;
    FLOAT MinPitchWS;
    FLOAT MaxPitchWS;
    FLOAT MinPitchCS;
    FLOAT MaxPitchCS;
    //## END PROPS OLAnimNotify_OverrideCameraParams

    DECLARE_CLASS(UOLAnimNotify_OverrideCameraParams,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("CameraParams"); }
};

class UOLAnimNotify_PlayWeaponAnimation : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_PlayWeaponAnimation
    //## END PROPS OLAnimNotify_PlayWeaponAnimation

    DECLARE_CLASS(UOLAnimNotify_PlayWeaponAnimation,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("PlayWeaponAnim"); }
};

class UOLAnimNotify_ProceduralAdjust : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_ProceduralAdjust
    FLOAT Duration;
    //## END PROPS OLAnimNotify_ProceduralAdjust

    DECLARE_CLASS(UOLAnimNotify_ProceduralAdjust,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("Procedural Adjust"); }
	virtual void AnimNotifyEventChanged(class UAnimNodeSequence* NodeSeq, FAnimNotifyEvent* OwnerEvent);
};

class UOLAnimNotify_PropAttachment : public UAnimNotify
{
public:
    //## BEGIN PROPS OLAnimNotify_PropAttachment
    BITFIELD bHideWhenDone:1;
    BITFIELD bDiscardOffsets:1;
    FLOAT BlendInTime;
    FLOAT BlendOutTime;
    FVector PositionOffset;
    FRotator OrientationOffset;
    FLOAT Duration;
    //## END PROPS OLAnimNotify_PropAttachment

    DECLARE_CLASS(UOLAnimNotify_PropAttachment,UAnimNotify,0,OLGame)
	virtual void Notify( class UAnimNodeSequence* NodeSeq );
	virtual FString GetEditorComment() { return TEXT("CSA Prop"); }
	virtual void AnimNotifyEventChanged(class UAnimNodeSequence* NodeSeq, FAnimNotifyEvent* OwnerEvent);
};

class UOLAnimParrying : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimParrying
    FLOAT MinimumDistance;
    FLOAT LowDistance;
    FLOAT HighDistance;
    FLOAT AngleRange;
    BITFIELD bActive:1;
    FLOAT EnemyDistance;
    FLOAT EnemyRelYaw;
    FLOAT ParryWeight;
    FLOAT ParryStrength;
    FLOAT ParryAngleRatio;
    //## END PROPS OLAnimParrying

    DECLARE_CLASS(UOLAnimParrying,UAnimNodeBlendBase,0,OLGame)
	virtual void TickAnim(FLOAT deltaSeconds);
	virtual void OnBecomeRelevant();
	
	void SetActive(UBOOL isActive);

private:
	enum { IdxNormal = 0, IdxLow = 1, IdxHigh = 2 };
};

class UOLAnimPeeking : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimPeeking
    INT ActiveChildIdx;
    FLOAT CurrentRatio;
    FLOAT TargetRatio;
    TArrayNoInit<FQuat> CornerToHandQuats;
    TArrayNoInit<FVector> CornerToHandVecs;
    //## END PROPS OLAnimPeeking

    DECLARE_CLASS(UOLAnimPeeking,UAnimNodeBlendBase,0,OLGame)
	void StartPeeking(FLOAT initialRatio);
	void SetPeekingType(UBOOL bFromLeft, UBOOL bRounded);
	void GetHandEffectorMtx(FMatrix& out_HandMtx, const FMatrix& cornerMtx, UBOOL bFromLeft, UBOOL bRounded);
	virtual void TickAnim(FLOAT deltaTime);

private:
	enum { IdxLeftHard = 0, IdxLeftSoft = 1, IdxRightHard = 2, IdxRightSoft = 3 };
};

class UOLAnimPushing : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimPushing
    FLOAT PushRatio;
    //## END PROPS OLAnimPushing

    DECLARE_CLASS(UOLAnimPushing,UAnimNodeBlendBase,0,OLGame)
	enum { IdxIdleLeft = 0, IdxIdleRight = 1, IdxLoopLeft = 2, IdxLoopRight = 3 };
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimRandomCycle : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimRandomCycle
    FLOAT DefaultCycleBiasWalking;
    FLOAT DefaultCycleBiasRunning;
    FLOAT BlendTime;
    FLOAT NextCycleCheckTime;
    BITFIELD bIsMaster:1;
    class UOLAnimRandomCycle* ShadowNode;
    //## END PROPS OLAnimRandomCycle

    DECLARE_CLASS(UOLAnimRandomCycle,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();

private:
	void StartNewCycle();
	void StartChild(INT childIdx);
	UAnimNodeSequence* GetAnimNodeForChild(INT childIdx);
};

class UOLAnimSelectByCamcorder : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimSelectByCamcorder
    //## END PROPS OLAnimSelectByCamcorder

    DECLARE_CLASS(UOLAnimSelectByCamcorder,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
};

class UOLAnimSelectByPhysicsVolume : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimSelectByPhysicsVolume
    //## END PROPS OLAnimSelectByPhysicsVolume

    DECLARE_CLASS(UOLAnimSelectByPhysicsVolume,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
};

class UOLAnimSelectByShadowProxy : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimSelectByShadowProxy
    //## END PROPS OLAnimSelectByShadowProxy

    DECLARE_CLASS(UOLAnimSelectByShadowProxy,UAnimNodeBlendList,0,OLGame)
	virtual void OnBecomeRelevant();
};

class UOLAnimSelectByWalkingStyle : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimSelectByWalkingStyle
    //## END PROPS OLAnimSelectByWalkingStyle

    DECLARE_CLASS(UOLAnimSelectByWalkingStyle,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
};

class UOLAnimSmartIdle : public UAnimNodeBlendBase
{
public:
    //## BEGIN PROPS OLAnimSmartIdle
    BITFIELD bModifyPlayrateIdle:1;
    FLOAT IdleMinRate;
    FLOAT IdleMaxRate;
    FLOAT IdleRateMinDuration;
    FLOAT IdleRateMaxDuration;
    FLOAT IdleRateTransitionSpeed;
    FLOAT IdleBias;
    FLOAT BreakerMaxWeight;
    FLOAT BreakerMinDuration;
    FLOAT BreakerMaxDuration;
    FLOAT MinBreakerWeightTransitionSpeed;
    FLOAT MaxBreakerWeightTransitionSpeed;
    FLOAT CurrentIdleRate;
    FLOAT TargetIdleRate;
    FLOAT NextIdleRateTransition;
    FLOAT CurrentBreakerWeight;
    FLOAT TargetBreakerWeight;
    FLOAT BreakerWeightTransitionSpeed;
    FLOAT NextBreakerWeightTransition;
    //## END PROPS OLAnimSmartIdle

    DECLARE_CLASS(UOLAnimSmartIdle,UAnimNodeBlendBase,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();

		// AnimTree editor interface
	virtual INT GetNumSliders() const { return 1; }
	virtual FLOAT GetSliderPosition(INT SliderIndex, INT ValueIndex);
	virtual FString GetSliderDrawValue(INT SliderIndex);

};

class UOLAnimStruggleCycle : public UAnimNodeSequence
{
public:
    //## BEGIN PROPS OLAnimStruggleCycle
    //## END PROPS OLAnimStruggleCycle

    DECLARE_CLASS(UOLAnimStruggleCycle,UAnimNodeSequence,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

class UOLAnimTurnOnSpot : public UAnimNodeBlendList
{
public:
    //## BEGIN PROPS OLAnimTurnOnSpot
    FLOAT CurrentFeetHeading;
    //## END PROPS OLAnimTurnOnSpot

    DECLARE_CLASS(UOLAnimTurnOnSpot,UAnimNodeBlendList,0,OLGame)
	virtual void TickAnim(FLOAT deltaTime);
	virtual void OnBecomeRelevant();
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_OLGAME_ANIM_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UOLAnimCustomBlend,-1,execPlayCustomBlendUC);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef OLGAME_ANIM_NATIVE_DEFS
#define OLGAME_ANIM_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_OLGAME_ANIM \
	UOLAnimBlendByEnemyEnvironment::StaticClass(); \
	UOLAnimBlendByEnemyMode::StaticClass(); \
	UOLAnimBlendByHobblingIntensity::StaticClass(); \
	UOLAnimBlendByIdle::StaticClass(); \
	UOLAnimBlendByLeaning::StaticClass(); \
	UOLAnimBlendByLocomotionMode::StaticClass(); \
	UOLAnimBlendByPosture::StaticClass(); \
	UOLAnimBlendBySpeed::StaticClass(); \
	UOLAnimBlendBySpeedExpandable::StaticClass(); \
	UOLAnimBlendBySwarmForm::StaticClass(); \
	UOLAnimBlendDirectional::StaticClass(); \
	UOLAnimCameraSpace::StaticClass(); \
	UOLAnimConstrainedMovement::StaticClass(); \
	UOLAnimCrouchedTurnOnSpot::StaticClass(); \
	UOLAnimCustomBlend::StaticClass(); \
	GNativeLookupFuncs.Set(FName("OLAnimCustomBlend"), GOLGameUOLAnimCustomBlendNatives); \
	UOLAnimCycleBreaker::StaticClass(); \
	UOLAnimSmarterIdle::StaticClass(); \
	UOLAnimDoorInteraction::StaticClass(); \
	UOLAnimEnemyStruggle::StaticClass(); \
	UOLAnimHeatShielding::StaticClass(); \
	UOLAnimLocomotion::StaticClass(); \
	UOLAnimMultiCycleConstrainedMovement::StaticClass(); \
	UOLAnimNodeDelayed::StaticClass(); \
	UOLAnimNodeSlot::StaticClass(); \
	UOLAnimNotify_AttachWeapon::StaticClass(); \
	UOLAnimNotify_Blur::StaticClass(); \
	UOLAnimNotify_Door::StaticClass(); \
	UOLAnimNotify_Fade::StaticClass(); \
	UOLAnimNotify_LeftHandIK::StaticClass(); \
	UOLAnimNotify_ModifyPlayrate::StaticClass(); \
	UOLAnimNotify_NonFatalDamage::StaticClass(); \
	UOLAnimNotify_OverrideCameraParams::StaticClass(); \
	UOLAnimNotify_PlayWeaponAnimation::StaticClass(); \
	UOLAnimNotify_ProceduralAdjust::StaticClass(); \
	UOLAnimNotify_PropAttachment::StaticClass(); \
	UOLAnimParrying::StaticClass(); \
	UOLAnimPeeking::StaticClass(); \
	UOLAnimPushing::StaticClass(); \
	UOLAnimRandomCycle::StaticClass(); \
	UOLAnimSelectByCamcorder::StaticClass(); \
	UOLAnimSelectByPhysicsVolume::StaticClass(); \
	UOLAnimSelectByShadowProxy::StaticClass(); \
	UOLAnimSelectByWalkingStyle::StaticClass(); \
	UOLAnimSmartIdle::StaticClass(); \
	UOLAnimStruggleCycle::StaticClass(); \
	UOLAnimTurnOnSpot::StaticClass(); \

#endif // OLGAME_ANIM_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GOLGameUOLAnimCustomBlendNatives[] = 
{ 
	MAP_NATIVE(UOLAnimCustomBlend, execPlayCustomBlendUC)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByEnemyEnvironment)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByEnemyMode)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByHobblingIntensity)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendByIdle,OLAnimBlendByIdle,ChildSynchGroup)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByIdle)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendByLeaning,OLAnimBlendByLeaning,CurrentRatio)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByLeaning)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendByLocomotionMode,OLAnimBlendByLocomotionMode,ChildBlendTimes)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByLocomotionMode)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendByPosture)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendBySpeed,OLAnimBlendBySpeed,MinSpeed)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendBySpeed,OLAnimBlendBySpeed,CurrentWeight)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendBySpeed)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendBySpeedExpandable,OLAnimBlendBySpeedExpandable,AnimSpeeds)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendBySpeedExpandable,OLAnimBlendBySpeedExpandable,SliderPosition)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendBySpeedExpandable)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendBySwarmForm)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendDirectional,OLAnimBlendDirectional,ExpectedPawnSpeed)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimBlendDirectional,OLAnimBlendDirectional,SliderDirAngle)
VERIFY_CLASS_SIZE_NODIE(UOLAnimBlendDirectional)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCameraSpace,OLAnimCameraSpace,ChildSlot)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCameraSpace,OLAnimCameraSpace,ParentChain)
VERIFY_CLASS_SIZE_NODIE(UOLAnimCameraSpace)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimConstrainedMovement,OLAnimConstrainedMovement,CurrentRatio)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimConstrainedMovement,OLAnimConstrainedMovement,NetSmoothedDelta)
VERIFY_CLASS_SIZE_NODIE(UOLAnimConstrainedMovement)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCrouchedTurnOnSpot,OLAnimCrouchedTurnOnSpot,BaseHeading)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCrouchedTurnOnSpot,OLAnimCrouchedTurnOnSpot,HandDownSound)
VERIFY_CLASS_SIZE_NODIE(UOLAnimCrouchedTurnOnSpot)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCustomBlend,OLAnimCustomBlend,BlendOutTime)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCustomBlend,OLAnimCustomBlend,NumActiveAnims)
VERIFY_CLASS_SIZE_NODIE(UOLAnimCustomBlend)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCycleBreaker,OLAnimCycleBreaker,DefaultCycleBias)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimCycleBreaker,OLAnimCycleBreaker,ValidBreakers)
VERIFY_CLASS_SIZE_NODIE(UOLAnimCycleBreaker)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimSmarterIdle,OLAnimSmarterIdle,IdleMinRate)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimSmarterIdle,OLAnimSmarterIdle,NextIdleRateTransition)
VERIFY_CLASS_SIZE_NODIE(UOLAnimSmarterIdle)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimDoorInteraction,OLAnimDoorInteraction,InitialRatio)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimDoorInteraction,OLAnimDoorInteraction,MaxRatio)
VERIFY_CLASS_SIZE_NODIE(UOLAnimDoorInteraction)
VERIFY_CLASS_SIZE_NODIE(UOLAnimEnemyStruggle)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimHeatShielding,OLAnimHeatShielding,MinimumDistance)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimHeatShielding,OLAnimHeatShielding,HeatStrength)
VERIFY_CLASS_SIZE_NODIE(UOLAnimHeatShielding)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimLocomotion,OLAnimLocomotion,MinMovingContribUnder90)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimLocomotion,OLAnimLocomotion,SliderPosition)
VERIFY_CLASS_SIZE_NODIE(UOLAnimLocomotion)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimMultiCycleConstrainedMovement,OLAnimMultiCycleConstrainedMovement,SmoothedDelta)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimMultiCycleConstrainedMovement,OLAnimMultiCycleConstrainedMovement,NetSmoothedDelta)
VERIFY_CLASS_SIZE_NODIE(UOLAnimMultiCycleConstrainedMovement)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNodeDelayed,OLAnimNodeDelayed,TimeDelay)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNodeDelayed,OLAnimNodeDelayed,ElapsedTime)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNodeDelayed)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNodeSlot)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_AttachWeapon,OLAnimNotify_AttachWeapon,WeaponSkelMesh)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_AttachWeapon,OLAnimNotify_AttachWeapon,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_AttachWeapon)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_Blur,OLAnimNotify_Blur,Amount)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_Blur,OLAnimNotify_Blur,Desaturation)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_Blur)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_Door,OLAnimNotify_Door,Interaction)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_Door,OLAnimNotify_Door,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_Door)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_Fade,OLAnimNotify_Fade,Opacity)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_Fade,OLAnimNotify_Fade,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_Fade)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_LeftHandIK,OLAnimNotify_LeftHandIK,TargetType)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_LeftHandIK,OLAnimNotify_LeftHandIK,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_LeftHandIK)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_ModifyPlayrate,OLAnimNotify_ModifyPlayrate,NewRate)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_ModifyPlayrate)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_NonFatalDamage,OLAnimNotify_NonFatalDamage,DamageAmount)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_NonFatalDamage)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_OverrideCameraParams,OLAnimNotify_OverrideCameraParams,MinYaw)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_OverrideCameraParams,OLAnimNotify_OverrideCameraParams,MaxPitchCS)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_OverrideCameraParams)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_PlayWeaponAnimation)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_ProceduralAdjust,OLAnimNotify_ProceduralAdjust,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_ProceduralAdjust)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_PropAttachment,OLAnimNotify_PropAttachment,BlendInTime)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimNotify_PropAttachment,OLAnimNotify_PropAttachment,Duration)
VERIFY_CLASS_SIZE_NODIE(UOLAnimNotify_PropAttachment)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimParrying,OLAnimParrying,MinimumDistance)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimParrying,OLAnimParrying,ParryAngleRatio)
VERIFY_CLASS_SIZE_NODIE(UOLAnimParrying)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimPeeking,OLAnimPeeking,ActiveChildIdx)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimPeeking,OLAnimPeeking,CornerToHandVecs)
VERIFY_CLASS_SIZE_NODIE(UOLAnimPeeking)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimPushing,OLAnimPushing,PushRatio)
VERIFY_CLASS_SIZE_NODIE(UOLAnimPushing)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimRandomCycle,OLAnimRandomCycle,DefaultCycleBiasWalking)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimRandomCycle,OLAnimRandomCycle,ShadowNode)
VERIFY_CLASS_SIZE_NODIE(UOLAnimRandomCycle)
VERIFY_CLASS_SIZE_NODIE(UOLAnimSelectByCamcorder)
VERIFY_CLASS_SIZE_NODIE(UOLAnimSelectByPhysicsVolume)
VERIFY_CLASS_SIZE_NODIE(UOLAnimSelectByShadowProxy)
VERIFY_CLASS_SIZE_NODIE(UOLAnimSelectByWalkingStyle)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimSmartIdle,OLAnimSmartIdle,IdleMinRate)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimSmartIdle,OLAnimSmartIdle,NextBreakerWeightTransition)
VERIFY_CLASS_SIZE_NODIE(UOLAnimSmartIdle)
VERIFY_CLASS_SIZE_NODIE(UOLAnimStruggleCycle)
VERIFY_CLASS_OFFSET_NODIE(UOLAnimTurnOnSpot,OLAnimTurnOnSpot,CurrentFeetHeading)
VERIFY_CLASS_SIZE_NODIE(UOLAnimTurnOnSpot)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
