/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
    Copyright 1998-2012 Epic Games, Inc. All Rights Reserved.
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#include "MultiplayerNames.h"

// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

#ifndef INCLUDED_MULTIPLAYER_ENUMS
#define INCLUDED_MULTIPLAYER_ENUMS 1


#endif // !INCLUDED_MULTIPLAYER_ENUMS
#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#ifndef INCLUDED_MULTIPLAYER_CLASSES
#define INCLUDED_MULTIPLAYER_CLASSES 1
#define ENABLE_DECLARECLASS_MACRO 1
#include "UnObjBas.h"
#undef ENABLE_DECLARECLASS_MACRO

class UDoorChannel : public UObject
{
public:
    //## BEGIN PROPS DoorChannel
    class AMultiplayerController* ControllerOwner;
    class AOLHero* HeroPawn;
    //## END PROPS DoorChannel

    virtual void TickSend(FLOAT DeltaTime);
    virtual void OnLocalDoorOpen(class AOLDoor* D);
    virtual void OnLocalDoorClose(class AOLDoor* D);
    virtual void OnDoorDeny(INT X,INT Y,INT Z);
    virtual void BroadcastDoorStates(const FString& LevelFilter);
    virtual void OnBinaryPacket(INT SenderID,BYTE PktType,BYTE* Data,INT DataLen);
    DECLARE_FUNCTION(execTickSend)
    {
        P_GET_FLOAT(DeltaTime);
        P_FINISH;
        this->TickSend(DeltaTime);
    }
    DECLARE_FUNCTION(execOnLocalDoorOpen)
    {
        P_GET_OBJECT(AOLDoor,D);
        P_FINISH;
        this->OnLocalDoorOpen(D);
    }
    DECLARE_FUNCTION(execOnLocalDoorClose)
    {
        P_GET_OBJECT(AOLDoor,D);
        P_FINISH;
        this->OnLocalDoorClose(D);
    }
    DECLARE_FUNCTION(execOnDoorDeny)
    {
        P_GET_INT(X);
        P_GET_INT(Y);
        P_GET_INT(Z);
        P_FINISH;
        this->OnDoorDeny(X,Y,Z);
    }
    DECLARE_FUNCTION(execBroadcastDoorStates)
    {
        P_GET_STR(LevelFilter);
        P_FINISH;
        this->BroadcastDoorStates(LevelFilter);
    }
    DECLARE_FUNCTION(execOnBinaryPacket)
    {
        P_GET_INT(SenderID);
        P_GET_BYTE(PktType);
        P_GET_ARRAY(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryPacket(SenderID,PktType,Data,DataLen);
    }
    DECLARE_CLASS(UDoorChannel,UObject,0,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(UDoorChannel)
};

class UEnemyChannel : public UObject
{
public:
    //## BEGIN PROPS EnemyChannel
    class AMultiplayerController* ControllerOwner;
    class AOLHero* HeroPawn;
    //## END PROPS EnemyChannel

    virtual void TickSend(FLOAT DeltaTime);
    virtual void SendSpawn(class AOLEnemyPawn* E);
    virtual void SendSMT(class AOLEnemyPawn* E,INT I);
    virtual void SendSMTDirect(class AOLEnemyPawn* E,INT SMTType,INT Param1,INT Param2);
    virtual void SendEnemyDoorOpen(class AOLEnemyPawn* Enemy,class AOLDoor* D,FLOAT Speed,FLOAT Angle);
    virtual void SendEnemyDoorDone(class AOLEnemyPawn* Enemy,class AOLDoor* D,FLOAT CloseSpeed);
    virtual void SendEnemyDoorBash(class AOLEnemyPawn* Enemy,class AOLDoor* D,UBOOL bReversed);
    virtual void SendEnemyDoorBreak(class AOLEnemyPawn* Enemy,class AOLDoor* D,UBOOL bReversed);
    virtual void SendAllDeletes();
    virtual void BroadcastSpawns();
    virtual void OnRequestEnemies(INT SenderID);
    virtual void OnBinaryLoc(INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnBinaryPacket(INT SenderID,BYTE PktType,BYTE* Data,INT DataLen);
    virtual class AOLEnemyPawn* FindEnemyByName(const FString& EnemyName);
    DECLARE_FUNCTION(execTickSend)
    {
        P_GET_FLOAT(DeltaTime);
        P_FINISH;
        this->TickSend(DeltaTime);
    }
    DECLARE_FUNCTION(execSendSpawn)
    {
        P_GET_OBJECT(AOLEnemyPawn,E);
        P_FINISH;
        this->SendSpawn(E);
    }
    DECLARE_FUNCTION(execSendSMT)
    {
        P_GET_OBJECT(AOLEnemyPawn,E);
        P_GET_INT(I);
        P_FINISH;
        this->SendSMT(E,I);
    }
    DECLARE_FUNCTION(execSendSMTDirect)
    {
        P_GET_OBJECT(AOLEnemyPawn,E);
        P_GET_INT(SMTType);
        P_GET_INT(Param1);
        P_GET_INT(Param2);
        P_FINISH;
        this->SendSMTDirect(E,SMTType,Param1,Param2);
    }
    DECLARE_FUNCTION(execSendEnemyDoorOpen)
    {
        P_GET_OBJECT(AOLEnemyPawn,Enemy);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_FLOAT(Speed);
        P_GET_FLOAT(Angle);
        P_FINISH;
        this->SendEnemyDoorOpen(Enemy,D,Speed,Angle);
    }
    DECLARE_FUNCTION(execSendEnemyDoorDone)
    {
        P_GET_OBJECT(AOLEnemyPawn,Enemy);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_FLOAT(CloseSpeed);
        P_FINISH;
        this->SendEnemyDoorDone(Enemy,D,CloseSpeed);
    }
    DECLARE_FUNCTION(execSendEnemyDoorBash)
    {
        P_GET_OBJECT(AOLEnemyPawn,Enemy);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_UBOOL(bReversed);
        P_FINISH;
        this->SendEnemyDoorBash(Enemy,D,bReversed);
    }
    DECLARE_FUNCTION(execSendEnemyDoorBreak)
    {
        P_GET_OBJECT(AOLEnemyPawn,Enemy);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_UBOOL(bReversed);
        P_FINISH;
        this->SendEnemyDoorBreak(Enemy,D,bReversed);
    }
    DECLARE_FUNCTION(execSendAllDeletes)
    {
        P_FINISH;
        this->SendAllDeletes();
    }
    DECLARE_FUNCTION(execBroadcastSpawns)
    {
        P_FINISH;
        this->BroadcastSpawns();
    }
    DECLARE_FUNCTION(execOnRequestEnemies)
    {
        P_GET_INT(SenderID);
        P_FINISH;
        this->OnRequestEnemies(SenderID);
    }
    DECLARE_FUNCTION(execOnBinaryLoc)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryLoc(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnBinaryPacket)
    {
        P_GET_INT(SenderID);
        P_GET_BYTE(PktType);
        P_GET_ARRAY(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryPacket(SenderID,PktType,Data,DataLen);
    }
    DECLARE_FUNCTION(execFindEnemyByName)
    {
        P_GET_STR(EnemyName);
        P_FINISH;
        *(class AOLEnemyPawn**)Result=this->FindEnemyByName(EnemyName);
    }
    DECLARE_CLASS(UEnemyChannel,UObject,0,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(UEnemyChannel)
};

class UHeroChannel : public UObject
{
public:
    //## BEGIN PROPS HeroChannel
    class AMultiplayerController* ControllerOwner;
    class AOLHero* HeroPawn;
    BITFIELD bSendingJumpGroundZ:1;
    FLOAT JumpGroundZ;
    INT LastSentSpecialMove;
    FStringNoInit LastSentCinematicAnim;
    INT LastSentMeshPreset;
    FVector LastPickupLoc;
    //## END PROPS HeroChannel

    virtual void SendGlobalState();
    virtual void SendHeadRotation();
    virtual void SendMesh();
    virtual void SendCinematicAnimation();
    virtual void SendSpecialMoveType();
    virtual void SendPickupStart(INT CurSMT);
    virtual void SendPickupState(INT CurSMT);
    virtual void SendCornerPeekData();
    virtual void SendPlayerHit(INT TargetPlayerID,FLOAT Damage,FLOAT KnockbackPower,FVector HitDir);
    virtual void SendPlayerGrab(INT TargetPlayerID,FVector GrabTargetLoc,FVector CharDir,UBOOL bCrouched,INT EnemyTypeInt,FLOAT BlendAlpha,UBOOL bLeftAnim,INT GrabType);
    virtual void SendPlayerThrow(INT TargetPlayerID,FLOAT ThrowRotation);
    virtual void SendPlayerKill(INT TargetPlayerID,INT EnemyTypeInt,INT WeaponType,UBOOL bBackAnim,UBOOL bLeftAnim,FLOAT BlendAlpha,FVector AnimStart,FVector CharDir,INT KillType,INT VictimYaw);
    virtual void OnBinaryLoc(INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnBinaryHeadRot(INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnBinaryMesh(INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnBinaryCinematicAnim(INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnBinarySmtType(INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnBinaryPlayerEvent(INT SenderID,BYTE* Data,INT DataLen);
    virtual void ApplyCamcorderState(INT Idx,class AOLHero* Dummy,INT NewCamcorderState);
    virtual void ApplySpecialMoveTransition(INT Idx,class AOLHero* Dummy,INT NewSpecialMove);
    virtual void ApplyLocomotionMode(INT Idx,class AOLHero* Dummy,INT NewLocomotionMode);
    virtual void SendPlayerDied();
    virtual void SendPlayerRespawned();
    virtual void SendDisconnect();
    virtual void SendRequestEnemies();
    virtual void SendRequestDoors();
    virtual void SendRequestPushables();
    virtual void OnBinaryPlayerLifecycle(INT SenderID,BYTE* Data,INT DataLen);
    DECLARE_FUNCTION(execSendGlobalState)
    {
        P_FINISH;
        this->SendGlobalState();
    }
    DECLARE_FUNCTION(execSendHeadRotation)
    {
        P_FINISH;
        this->SendHeadRotation();
    }
    DECLARE_FUNCTION(execSendMesh)
    {
        P_FINISH;
        this->SendMesh();
    }
    DECLARE_FUNCTION(execSendCinematicAnimation)
    {
        P_FINISH;
        this->SendCinematicAnimation();
    }
    DECLARE_FUNCTION(execSendSpecialMoveType)
    {
        P_FINISH;
        this->SendSpecialMoveType();
    }
    DECLARE_FUNCTION(execSendPickupStart)
    {
        P_GET_INT(CurSMT);
        P_FINISH;
        this->SendPickupStart(CurSMT);
    }
    DECLARE_FUNCTION(execSendPickupState)
    {
        P_GET_INT(CurSMT);
        P_FINISH;
        this->SendPickupState(CurSMT);
    }
    DECLARE_FUNCTION(execSendCornerPeekData)
    {
        P_FINISH;
        this->SendCornerPeekData();
    }
    DECLARE_FUNCTION(execSendPlayerHit)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_FLOAT(Damage);
        P_GET_FLOAT(KnockbackPower);
        P_GET_STRUCT(FVector,HitDir);
        P_FINISH;
        this->SendPlayerHit(TargetPlayerID,Damage,KnockbackPower,HitDir);
    }
    DECLARE_FUNCTION(execSendPlayerGrab)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_STRUCT(FVector,GrabTargetLoc);
        P_GET_STRUCT(FVector,CharDir);
        P_GET_UBOOL(bCrouched);
        P_GET_INT(EnemyTypeInt);
        P_GET_FLOAT(BlendAlpha);
        P_GET_UBOOL(bLeftAnim);
        P_GET_INT(GrabType);
        P_FINISH;
        this->SendPlayerGrab(TargetPlayerID,GrabTargetLoc,CharDir,bCrouched,EnemyTypeInt,BlendAlpha,bLeftAnim,GrabType);
    }
    DECLARE_FUNCTION(execSendPlayerThrow)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_FLOAT(ThrowRotation);
        P_FINISH;
        this->SendPlayerThrow(TargetPlayerID,ThrowRotation);
    }
    DECLARE_FUNCTION(execSendPlayerKill)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_INT(EnemyTypeInt);
        P_GET_INT(WeaponType);
        P_GET_UBOOL(bBackAnim);
        P_GET_UBOOL(bLeftAnim);
        P_GET_FLOAT(BlendAlpha);
        P_GET_STRUCT(FVector,AnimStart);
        P_GET_STRUCT(FVector,CharDir);
        P_GET_INT(KillType);
        P_GET_INT(VictimYaw);
        P_FINISH;
        this->SendPlayerKill(TargetPlayerID,EnemyTypeInt,WeaponType,bBackAnim,bLeftAnim,BlendAlpha,AnimStart,CharDir,KillType,VictimYaw);
    }
    DECLARE_FUNCTION(execOnBinaryLoc)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryLoc(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnBinaryHeadRot)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryHeadRot(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnBinaryMesh)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryMesh(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnBinaryCinematicAnim)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryCinematicAnim(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnBinarySmtType)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinarySmtType(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnBinaryPlayerEvent)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryPlayerEvent(SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execApplyCamcorderState)
    {
        P_GET_INT(Idx);
        P_GET_OBJECT(AOLHero,Dummy);
        P_GET_INT(NewCamcorderState);
        P_FINISH;
        this->ApplyCamcorderState(Idx,Dummy,NewCamcorderState);
    }
    DECLARE_FUNCTION(execApplySpecialMoveTransition)
    {
        P_GET_INT(Idx);
        P_GET_OBJECT(AOLHero,Dummy);
        P_GET_INT(NewSpecialMove);
        P_FINISH;
        this->ApplySpecialMoveTransition(Idx,Dummy,NewSpecialMove);
    }
    DECLARE_FUNCTION(execApplyLocomotionMode)
    {
        P_GET_INT(Idx);
        P_GET_OBJECT(AOLHero,Dummy);
        P_GET_INT(NewLocomotionMode);
        P_FINISH;
        this->ApplyLocomotionMode(Idx,Dummy,NewLocomotionMode);
    }
    DECLARE_FUNCTION(execSendPlayerDied)
    {
        P_FINISH;
        this->SendPlayerDied();
    }
    DECLARE_FUNCTION(execSendPlayerRespawned)
    {
        P_FINISH;
        this->SendPlayerRespawned();
    }
    DECLARE_FUNCTION(execSendDisconnect)
    {
        P_FINISH;
        this->SendDisconnect();
    }
    DECLARE_FUNCTION(execSendRequestEnemies)
    {
        P_FINISH;
        this->SendRequestEnemies();
    }
    DECLARE_FUNCTION(execSendRequestDoors)
    {
        P_FINISH;
        this->SendRequestDoors();
    }
    DECLARE_FUNCTION(execSendRequestPushables)
    {
        P_FINISH;
        this->SendRequestPushables();
    }
    DECLARE_FUNCTION(execOnBinaryPlayerLifecycle)
    {
        P_GET_INT(SenderID);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryPlayerLifecycle(SenderID,Data,DataLen);
    }
    DECLARE_CLASS(UHeroChannel,UObject,0,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(UHeroChannel)
};

struct MultiplayerController_eventOnPlayerDisconnected_Parms
{
    INT PlayerID;
    MultiplayerController_eventOnPlayerDisconnected_Parms(EEventParm)
    {
    }
};
class AMultiplayerController : public AOLPlayerController
{
public:
    //## BEGIN PROPS MultiplayerController
    class UHeroChannel* HeroChannel;
    class UDoorChannel* DoorChannel;
    class UPushableChannel* PushableChannel;
    class UEnemyChannel* EnemyChannel;
    class UWorldChannel* WorldChannel;
    INT OnlineCount;
    FLOAT CurrentPingMs;
    FLOAT LastPongTime;
    FStringNoInit ServerName;
    BITFIELD bSentPlayerDied:1;
    BITFIELD bDoorsIndexed:1;
    BITFIELD bPushablesIndexed:1;
    TArrayNoInit<class URemotePlayer*> RemotePlayers;
    TArrayNoInit<class AActor*> CachedDoors;
    TArrayNoInit<FPendingDoorState> PendingDoorStates;
    TArrayNoInit<FLOAT> LastSentDoorAngle;
    TArrayNoInit<FLOAT> RemoteDoorLockExpiry;
    TArrayNoInit<class AOLPushableObject*> CachedPushables;
    TArrayNoInit<FPendingPushState> PendingPushStates;
    TArrayNoInit<FLOAT> LastSentPushDisplacement;
    TArrayNoInit<class AOLEnemyPawn*> CachedEnemies;
    TArrayNoInit<UBOOL> LastEnemyAlive;
    TArrayNoInit<INT> LastEnemySMT;
    TArrayNoInit<FLOAT> LastBashLoopSentTime;
    TArrayNoInit<FRemoteEnemyState> RemoteEnemies;
    TArrayNoInit<FString> SentEnemySpawns;
    TArrayNoInit<FString> TriggerActBlacklist;
    TArrayNoInit<FString> CSAActBlacklist;
    //## END PROPS MultiplayerController

    virtual FString NativeGetUsername();
    virtual void NativeInit();
    virtual UBOOL IsConnected();
    virtual UBOOL IsReady();
    virtual INT FindRemoteIndex(INT PlayerID);
    virtual INT RegisterRemotePlayer(INT PlayerID,const FString& Nick);
    virtual void NativeSetHero(class AOLHero* Hero);
    virtual void OnReceiveData(const FString& Data);
    virtual void OnReceiveBinaryData(BYTE PktType,INT SenderID,BYTE* Data,INT DataLen);
    virtual void OnConnected();
    virtual void OnDisconnected();
    virtual void NativeRemoveRemotePlayer(INT PlayerID);
    virtual void NativeDestroyRemoteEnemies();
    virtual UBOOL IndexDoors();
    virtual void IndexEnemies();
    virtual UBOOL IndexPushables();
    virtual void ApplyPendingPushStates();
    virtual void RemoveRemotePlayer(INT PlayerID);
    virtual void DestroyRemoteEnemies();
    virtual void NotifyDummyPlayerHit(class AOLHero* DummyTarget,FLOAT Damage,FLOAT KnockbackPower,FVector HitDir);
    virtual void NotifyDummyPlayerGrab(INT TargetPlayerID,FVector GrabTargetLoc,FVector CharDir,UBOOL bCrouched,INT EnemyTypeInt,FLOAT BlendAlpha,UBOOL bLeftAnim,INT GrabType);
    virtual void NotifyDummyPlayerThrow(INT TargetPlayerID,FLOAT ThrowRotation);
    virtual void NotifyDummyPlayerKill(INT TargetPlayerID,INT EnemyTypeInt,INT WeaponType,UBOOL bBackAnim,UBOOL bLeftAnim,FLOAT BlendAlpha,FVector AnimStart,FVector CharDir,INT KillType,INT VictimYaw);
    virtual void NotifyDummyEnemySMT(class AOLEnemyPawn* EnemyPawn,INT SMTType,INT Param1,INT Param2);
    virtual void NativeNotifyEnemyDoorOpen(class AOLEnemyPawn* EnemyPawn,class AOLDoor* D,FLOAT Speed,FLOAT Angle);
    virtual void NativeNotifyEnemyDoorDone(class AOLEnemyPawn* EnemyPawn,class AOLDoor* D,FLOAT CloseSpeed);
    virtual void NotifyEnemyDoorBash(class AOLEnemyPawn* EnemyPawn,class AOLDoor* D,UBOOL bReversed);
    virtual void NotifyEnemyDoorBreak(class AOLEnemyPawn* EnemyPawn,class AOLDoor* D,UBOOL bReversed);
    virtual void NotifyPawnTouchedTrigger(class AActor* TriggerActor);
    virtual void OnInventoryItemConsumed(FName ItemName);
    virtual void OnPickupKismetEvent(class AOLPickableObject* Pickup);
    virtual void OnLocalDoorOpen(class AOLDoor* D);
    virtual void OnLocalDoorClose(class AOLDoor* D);
    virtual void OnRecordingMarkerCompleted(class AOLRecordingMarker* Marker);
    virtual void OnToggleCinematicMode(class USeqAct_ToggleCinematicMode* Action);
    virtual void InterpolationStarted(class USeqAct_Interp* InterpAction,class UInterpGroupInst* GroupInst);
    virtual void InterpolationFinished(class USeqAct_Interp* InterpAction);
    virtual void NativeDestroyed();
    DECLARE_FUNCTION(execNativeGetUsername)
    {
        P_FINISH;
        *(FString*)Result=this->NativeGetUsername();
    }
    DECLARE_FUNCTION(execNativeInit)
    {
        P_FINISH;
        this->NativeInit();
    }
    DECLARE_FUNCTION(execIsConnected)
    {
        P_FINISH;
        *(UBOOL*)Result=this->IsConnected();
    }
    DECLARE_FUNCTION(execIsReady)
    {
        P_FINISH;
        *(UBOOL*)Result=this->IsReady();
    }
    DECLARE_FUNCTION(execFindRemoteIndex)
    {
        P_GET_INT(PlayerID);
        P_FINISH;
        *(INT*)Result=this->FindRemoteIndex(PlayerID);
    }
    DECLARE_FUNCTION(execRegisterRemotePlayer)
    {
        P_GET_INT(PlayerID);
        P_GET_STR(Nick);
        P_FINISH;
        *(INT*)Result=this->RegisterRemotePlayer(PlayerID,Nick);
    }
    DECLARE_FUNCTION(execNativeSetHero)
    {
        P_GET_OBJECT(AOLHero,Hero);
        P_FINISH;
        this->NativeSetHero(Hero);
    }
    DECLARE_FUNCTION(execOnReceiveData)
    {
        P_GET_STR(Data);
        P_FINISH;
        this->OnReceiveData(Data);
    }
    DECLARE_FUNCTION(execOnReceiveBinaryData)
    {
        P_GET_BYTE(PktType);
        P_GET_INT(SenderID);
        P_GET_ARRAY(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnReceiveBinaryData(PktType,SenderID,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnConnected)
    {
        P_FINISH;
        this->OnConnected();
    }
    DECLARE_FUNCTION(execOnDisconnected)
    {
        P_FINISH;
        this->OnDisconnected();
    }
    DECLARE_FUNCTION(execNativeRemoveRemotePlayer)
    {
        P_GET_INT(PlayerID);
        P_FINISH;
        this->NativeRemoveRemotePlayer(PlayerID);
    }
    DECLARE_FUNCTION(execNativeDestroyRemoteEnemies)
    {
        P_FINISH;
        this->NativeDestroyRemoteEnemies();
    }
    DECLARE_FUNCTION(execIndexDoors)
    {
        P_FINISH;
        *(UBOOL*)Result=this->IndexDoors();
    }
    DECLARE_FUNCTION(execIndexEnemies)
    {
        P_FINISH;
        this->IndexEnemies();
    }
    DECLARE_FUNCTION(execIndexPushables)
    {
        P_FINISH;
        *(UBOOL*)Result=this->IndexPushables();
    }
    DECLARE_FUNCTION(execApplyPendingPushStates)
    {
        P_FINISH;
        this->ApplyPendingPushStates();
    }
    DECLARE_FUNCTION(execRemoveRemotePlayer)
    {
        P_GET_INT(PlayerID);
        P_FINISH;
        this->RemoveRemotePlayer(PlayerID);
    }
    DECLARE_FUNCTION(execDestroyRemoteEnemies)
    {
        P_FINISH;
        this->DestroyRemoteEnemies();
    }
    DECLARE_FUNCTION(execNotifyDummyPlayerHit)
    {
        P_GET_OBJECT(AOLHero,DummyTarget);
        P_GET_FLOAT(Damage);
        P_GET_FLOAT(KnockbackPower);
        P_GET_STRUCT(FVector,HitDir);
        P_FINISH;
        this->NotifyDummyPlayerHit(DummyTarget,Damage,KnockbackPower,HitDir);
    }
    DECLARE_FUNCTION(execNotifyDummyPlayerGrab)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_STRUCT(FVector,GrabTargetLoc);
        P_GET_STRUCT(FVector,CharDir);
        P_GET_UBOOL(bCrouched);
        P_GET_INT(EnemyTypeInt);
        P_GET_FLOAT(BlendAlpha);
        P_GET_UBOOL(bLeftAnim);
        P_GET_INT(GrabType);
        P_FINISH;
        this->NotifyDummyPlayerGrab(TargetPlayerID,GrabTargetLoc,CharDir,bCrouched,EnemyTypeInt,BlendAlpha,bLeftAnim,GrabType);
    }
    DECLARE_FUNCTION(execNotifyDummyPlayerThrow)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_FLOAT(ThrowRotation);
        P_FINISH;
        this->NotifyDummyPlayerThrow(TargetPlayerID,ThrowRotation);
    }
    DECLARE_FUNCTION(execNotifyDummyPlayerKill)
    {
        P_GET_INT(TargetPlayerID);
        P_GET_INT(EnemyTypeInt);
        P_GET_INT(WeaponType);
        P_GET_UBOOL(bBackAnim);
        P_GET_UBOOL(bLeftAnim);
        P_GET_FLOAT(BlendAlpha);
        P_GET_STRUCT(FVector,AnimStart);
        P_GET_STRUCT(FVector,CharDir);
        P_GET_INT(KillType);
        P_GET_INT(VictimYaw);
        P_FINISH;
        this->NotifyDummyPlayerKill(TargetPlayerID,EnemyTypeInt,WeaponType,bBackAnim,bLeftAnim,BlendAlpha,AnimStart,CharDir,KillType,VictimYaw);
    }
    DECLARE_FUNCTION(execNotifyDummyEnemySMT)
    {
        P_GET_OBJECT(AOLEnemyPawn,EnemyPawn);
        P_GET_INT(SMTType);
        P_GET_INT(Param1);
        P_GET_INT(Param2);
        P_FINISH;
        this->NotifyDummyEnemySMT(EnemyPawn,SMTType,Param1,Param2);
    }
    DECLARE_FUNCTION(execNativeNotifyEnemyDoorOpen)
    {
        P_GET_OBJECT(AOLEnemyPawn,EnemyPawn);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_FLOAT(Speed);
        P_GET_FLOAT(Angle);
        P_FINISH;
        this->NativeNotifyEnemyDoorOpen(EnemyPawn,D,Speed,Angle);
    }
    DECLARE_FUNCTION(execNativeNotifyEnemyDoorDone)
    {
        P_GET_OBJECT(AOLEnemyPawn,EnemyPawn);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_FLOAT(CloseSpeed);
        P_FINISH;
        this->NativeNotifyEnemyDoorDone(EnemyPawn,D,CloseSpeed);
    }
    DECLARE_FUNCTION(execNotifyEnemyDoorBash)
    {
        P_GET_OBJECT(AOLEnemyPawn,EnemyPawn);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_UBOOL(bReversed);
        P_FINISH;
        this->NotifyEnemyDoorBash(EnemyPawn,D,bReversed);
    }
    DECLARE_FUNCTION(execNotifyEnemyDoorBreak)
    {
        P_GET_OBJECT(AOLEnemyPawn,EnemyPawn);
        P_GET_OBJECT(AOLDoor,D);
        P_GET_UBOOL(bReversed);
        P_FINISH;
        this->NotifyEnemyDoorBreak(EnemyPawn,D,bReversed);
    }
    DECLARE_FUNCTION(execNotifyPawnTouchedTrigger)
    {
        P_GET_OBJECT(AActor,TriggerActor);
        P_FINISH;
        this->NotifyPawnTouchedTrigger(TriggerActor);
    }
    DECLARE_FUNCTION(execOnInventoryItemConsumed)
    {
        P_GET_NAME(ItemName);
        P_FINISH;
        this->OnInventoryItemConsumed(ItemName);
    }
    DECLARE_FUNCTION(execOnPickupKismetEvent)
    {
        P_GET_OBJECT(AOLPickableObject,Pickup);
        P_FINISH;
        this->OnPickupKismetEvent(Pickup);
    }
    DECLARE_FUNCTION(execOnLocalDoorOpen)
    {
        P_GET_OBJECT(AOLDoor,D);
        P_FINISH;
        this->OnLocalDoorOpen(D);
    }
    DECLARE_FUNCTION(execOnLocalDoorClose)
    {
        P_GET_OBJECT(AOLDoor,D);
        P_FINISH;
        this->OnLocalDoorClose(D);
    }
    DECLARE_FUNCTION(execOnRecordingMarkerCompleted)
    {
        P_GET_OBJECT(AOLRecordingMarker,Marker);
        P_FINISH;
        this->OnRecordingMarkerCompleted(Marker);
    }
    DECLARE_FUNCTION(execOnToggleCinematicMode)
    {
        P_GET_OBJECT(USeqAct_ToggleCinematicMode,Action);
        P_FINISH;
        this->OnToggleCinematicMode(Action);
    }
    DECLARE_FUNCTION(execInterpolationStarted)
    {
        P_GET_OBJECT(USeqAct_Interp,InterpAction);
        P_GET_OBJECT(UInterpGroupInst,GroupInst);
        P_FINISH;
        this->InterpolationStarted(InterpAction,GroupInst);
    }
    DECLARE_FUNCTION(execInterpolationFinished)
    {
        P_GET_OBJECT(USeqAct_Interp,InterpAction);
        P_FINISH;
        this->InterpolationFinished(InterpAction);
    }
    DECLARE_FUNCTION(execNativeDestroyed)
    {
        P_FINISH;
        this->NativeDestroyed();
    }
    void eventOnPlayerDisconnected(INT PlayerID)
    {
        MultiplayerController_eventOnPlayerDisconnected_Parms Parms(EC_EventParm);
        Parms.PlayerID=PlayerID;
        ProcessEvent(FindFunctionChecked(MULTIPLAYER_OnPlayerDisconnected),&Parms);
    }
    DECLARE_CLASS(AMultiplayerController,AOLPlayerController,0|CLASS_Config,Multiplayer)
    static const TCHAR* StaticConfigName() {return TEXT("Multiplayer");}

    NO_DEFAULT_CONSTRUCTOR(AMultiplayerController)
};

class AMultiplayerHero : public AOLHero
{
public:
    //## BEGIN PROPS MultiplayerHero
    //## END PROPS MultiplayerHero

    DECLARE_CLASS(AMultiplayerHero,AOLHero,0|CLASS_Config,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(AMultiplayerHero)
};

#define UCONST_NOTIF_FADE_OUT 0.6
#define UCONST_NOTIF_FADE_IN 0.25
#define UCONST_NOTIF_DURATION 5.0

class AMultiplayerHUD : public AOLHUD
{
public:
    //## BEGIN PROPS MultiplayerHUD
    INT MaxNickDisplay;
    TArrayNoInit<FNotificationEntry> Notifications;
    //## END PROPS MultiplayerHUD

    virtual void AddNotification(const FString& msg);
    DECLARE_FUNCTION(execAddNotification)
    {
        P_GET_STR(msg);
        P_FINISH;
        this->AddNotification(msg);
    }
    DECLARE_CLASS(AMultiplayerHUD,AOLHUD,0|CLASS_Transient|CLASS_Config,Multiplayer)
    static const TCHAR* StaticConfigName() {return TEXT("Multiplayer");}

    NO_DEFAULT_CONSTRUCTOR(AMultiplayerHUD)
};

class AMultiplayerLink : public AUdpLink
{
public:
    //## BEGIN PROPS MultiplayerLink
    //## END PROPS MultiplayerLink

    void NativeReloadConfig();
    DECLARE_FUNCTION(execNativeReloadConfig)
    {
        P_FINISH;
        this->NativeReloadConfig();
    }
    DECLARE_CLASS(AMultiplayerLink,AUdpLink,0|CLASS_Transient,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(AMultiplayerLink)
};

class UPushableChannel : public UObject
{
public:
    //## BEGIN PROPS PushableChannel
    class AMultiplayerController* ControllerOwner;
    class AOLHero* HeroPawn;
    //## END PROPS PushableChannel

    virtual void TickSend(FLOAT DeltaTime);
    virtual void BroadcastPushableStates();
    virtual class AOLPushableObject* FindPushableByKey(INT KeyX,INT KeyY,INT KeyZ);
    DECLARE_FUNCTION(execTickSend)
    {
        P_GET_FLOAT(DeltaTime);
        P_FINISH;
        this->TickSend(DeltaTime);
    }
    DECLARE_FUNCTION(execBroadcastPushableStates)
    {
        P_FINISH;
        this->BroadcastPushableStates();
    }
    DECLARE_FUNCTION(execFindPushableByKey)
    {
        P_GET_INT(KeyX);
        P_GET_INT(KeyY);
        P_GET_INT(KeyZ);
        P_FINISH;
        *(class AOLPushableObject**)Result=this->FindPushableByKey(KeyX,KeyY,KeyZ);
    }
    DECLARE_CLASS(UPushableChannel,UObject,0,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(UPushableChannel)
};

class URemotePlayer : public UObject
{
public:
    //## BEGIN PROPS RemotePlayer
    class AMultiplayerController* ControllerOwner;
    INT PlayerID;
    FStringNoInit PlayerNick;
    FStringNoInit Nick;
    class APawn* DummyPlayer;
    FVector LastReceivedLoc;
    FVector LastReceivedVel;
    FRotator LastReceivedRot;
    BITFIELD bHasReceivedData:1;
    BITFIELD bLastRemoteCrouched:1;
    BITFIELD bDummyCrouched:1;
    BITFIELD bLastRemoteHeatShielding:1;
    BITFIELD bJumpOverActive:1;
    BITFIELD bLastRemoteDoorQuiet:1;
    BITFIELD bLastRemotePushFromBack:1;
    BITFIELD bLastRemotePeekFromLeft:1;
    BITFIELD bLastRemotePeekRounded:1;
    BITFIELD bPeekTypeApplied:1;
    INT LastRemoteSpecialMove;
    INT PendingSMT;
    FVector PendingSMTGrabPos;
    FVector PendingSMTGrabDir;
    FLOAT DummySMTLockUntil;
    INT LastRemoteLocomotionMode;
    INT LastRemoteHealth;
    INT LastRemoteCamPitch;
    INT LastRemoteCamYaw;
    INT LastRemoteCamcorderState;
    FLOAT LastRemoteHeatDistance;
    FLOAT JumpGroundZ;
    INT LockedDoorIdx;
    INT LastRemoteDoorOpeningType;
    INT LastRemoteDoorPartialOpenType;
    INT LastRemoteDoorClosingType;
    FVector LastRemoteDoorHandlePos;
    FVector LastRemoteCornerLocation;
    FVector LastRemoteCornerFwdDir;
    FVector LastRemotePickupLoc;
    //## END PROPS RemotePlayer

    virtual void Tick(FLOAT DeltaTime);
    DECLARE_FUNCTION(execTick)
    {
        P_GET_FLOAT(DeltaTime);
        P_FINISH;
        this->Tick(DeltaTime);
    }
    DECLARE_CLASS(URemotePlayer,UObject,0,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(URemotePlayer)
};

class UWorldChannel : public UObject
{
public:
    //## BEGIN PROPS WorldChannel
    class AMultiplayerController* ControllerOwner;
    class AOLHero* HeroPawn;
    //## END PROPS WorldChannel

    virtual void SendPickupState(INT CurSMT);
    virtual void SendPickupKismet(class AOLPickableObject* Pickup);
    virtual void SendItemConsume(FName ItemName);
    virtual void SendRecordingMarker(class AOLRecordingMarker* Marker);
    virtual void SendMatineeState();
    virtual void OnPawnTouchedTrigger(class AActor* TriggerActor);
    virtual void OnBinaryNick(INT SenderID,const FString& Nick);
    virtual void OnBinaryWorldPacket(INT SenderID,BYTE PktType,BYTE* Data,INT DataLen);
    virtual void OnDisconnected(const TArray<FString>& Parts,INT SenderID);
    DECLARE_FUNCTION(execSendPickupState)
    {
        P_GET_INT(CurSMT);
        P_FINISH;
        this->SendPickupState(CurSMT);
    }
    DECLARE_FUNCTION(execSendPickupKismet)
    {
        P_GET_OBJECT(AOLPickableObject,Pickup);
        P_FINISH;
        this->SendPickupKismet(Pickup);
    }
    DECLARE_FUNCTION(execSendItemConsume)
    {
        P_GET_NAME(ItemName);
        P_FINISH;
        this->SendItemConsume(ItemName);
    }
    DECLARE_FUNCTION(execSendRecordingMarker)
    {
        P_GET_OBJECT(AOLRecordingMarker,Marker);
        P_FINISH;
        this->SendRecordingMarker(Marker);
    }
    DECLARE_FUNCTION(execSendMatineeState)
    {
        P_FINISH;
        this->SendMatineeState();
    }
    DECLARE_FUNCTION(execOnPawnTouchedTrigger)
    {
        P_GET_OBJECT(AActor,TriggerActor);
        P_FINISH;
        this->OnPawnTouchedTrigger(TriggerActor);
    }
    DECLARE_FUNCTION(execOnBinaryNick)
    {
        P_GET_INT(SenderID);
        P_GET_STR(Nick);
        P_FINISH;
        this->OnBinaryNick(SenderID,Nick);
    }
    DECLARE_FUNCTION(execOnBinaryWorldPacket)
    {
        P_GET_INT(SenderID);
        P_GET_BYTE(PktType);
        P_GET_ARRAY_REF(BYTE,Data);
        P_GET_INT(DataLen);
        P_FINISH;
        this->OnBinaryWorldPacket(SenderID,PktType,Data,DataLen);
    }
    DECLARE_FUNCTION(execOnDisconnected)
    {
        P_GET_TARRAY(FString,Parts);
        P_GET_INT(SenderID);
        P_FINISH;
        this->OnDisconnected(Parts,SenderID);
    }
    DECLARE_CLASS(UWorldChannel,UObject,0,Multiplayer)
    NO_DEFAULT_CONSTRUCTOR(UWorldChannel)
};

#undef DECLARE_CLASS
#undef DECLARE_CASTED_CLASS
#undef DECLARE_ABSTRACT_CLASS
#undef DECLARE_ABSTRACT_CASTED_CLASS
#endif // !INCLUDED_MULTIPLAYER_CLASSES
#endif // !NAMES_ONLY

AUTOGENERATE_FUNCTION(UDoorChannel,-1,execOnBinaryPacket);
AUTOGENERATE_FUNCTION(UDoorChannel,-1,execBroadcastDoorStates);
AUTOGENERATE_FUNCTION(UDoorChannel,-1,execOnDoorDeny);
AUTOGENERATE_FUNCTION(UDoorChannel,-1,execOnLocalDoorClose);
AUTOGENERATE_FUNCTION(UDoorChannel,-1,execOnLocalDoorOpen);
AUTOGENERATE_FUNCTION(UDoorChannel,-1,execTickSend);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execFindEnemyByName);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execOnBinaryPacket);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execOnBinaryLoc);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execOnRequestEnemies);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execBroadcastSpawns);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendAllDeletes);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendEnemyDoorBreak);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendEnemyDoorBash);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendEnemyDoorDone);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendEnemyDoorOpen);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendSMTDirect);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendSMT);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execSendSpawn);
AUTOGENERATE_FUNCTION(UEnemyChannel,-1,execTickSend);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinaryPlayerLifecycle);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendRequestPushables);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendRequestDoors);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendRequestEnemies);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendDisconnect);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPlayerRespawned);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPlayerDied);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execApplyLocomotionMode);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execApplySpecialMoveTransition);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execApplyCamcorderState);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinaryPlayerEvent);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinarySmtType);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinaryCinematicAnim);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinaryMesh);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinaryHeadRot);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execOnBinaryLoc);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPlayerKill);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPlayerThrow);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPlayerGrab);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPlayerHit);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendCornerPeekData);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPickupState);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendPickupStart);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendSpecialMoveType);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendCinematicAnimation);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendMesh);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendHeadRotation);
AUTOGENERATE_FUNCTION(UHeroChannel,-1,execSendGlobalState);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeDestroyed);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execInterpolationFinished);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execInterpolationStarted);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnToggleCinematicMode);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnRecordingMarkerCompleted);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnLocalDoorClose);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnLocalDoorOpen);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnPickupKismetEvent);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnInventoryItemConsumed);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyPawnTouchedTrigger);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyEnemyDoorBreak);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyEnemyDoorBash);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeNotifyEnemyDoorDone);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeNotifyEnemyDoorOpen);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyDummyEnemySMT);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyDummyPlayerKill);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyDummyPlayerThrow);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyDummyPlayerGrab);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNotifyDummyPlayerHit);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execDestroyRemoteEnemies);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execRemoveRemotePlayer);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execApplyPendingPushStates);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execIndexPushables);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execIndexEnemies);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execIndexDoors);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeDestroyRemoteEnemies);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeRemoveRemotePlayer);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnDisconnected);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnConnected);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnReceiveBinaryData);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execOnReceiveData);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeSetHero);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execRegisterRemotePlayer);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execFindRemoteIndex);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execIsReady);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execIsConnected);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeInit);
AUTOGENERATE_FUNCTION(AMultiplayerController,-1,execNativeGetUsername);
AUTOGENERATE_FUNCTION(AMultiplayerHUD,-1,execAddNotification);
AUTOGENERATE_FUNCTION(AMultiplayerLink,-1,execNativeReloadConfig);
AUTOGENERATE_FUNCTION(UPushableChannel,-1,execFindPushableByKey);
AUTOGENERATE_FUNCTION(UPushableChannel,-1,execBroadcastPushableStates);
AUTOGENERATE_FUNCTION(UPushableChannel,-1,execTickSend);
AUTOGENERATE_FUNCTION(URemotePlayer,-1,execTick);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execOnDisconnected);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execOnBinaryWorldPacket);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execOnBinaryNick);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execOnPawnTouchedTrigger);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execSendMatineeState);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execSendRecordingMarker);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execSendItemConsume);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execSendPickupKismet);
AUTOGENERATE_FUNCTION(UWorldChannel,-1,execSendPickupState);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef MULTIPLAYER_NATIVE_DEFS
#define MULTIPLAYER_NATIVE_DEFS

#define AUTO_INITIALIZE_REGISTRANTS_MULTIPLAYER \
	UDoorChannel::StaticClass(); \
	GNativeLookupFuncs.Set(FName("DoorChannel"), GMultiplayerUDoorChannelNatives); \
	UEnemyChannel::StaticClass(); \
	GNativeLookupFuncs.Set(FName("EnemyChannel"), GMultiplayerUEnemyChannelNatives); \
	UHeroChannel::StaticClass(); \
	GNativeLookupFuncs.Set(FName("HeroChannel"), GMultiplayerUHeroChannelNatives); \
	AMultiplayerController::StaticClass(); \
	GNativeLookupFuncs.Set(FName("MultiplayerController"), GMultiplayerAMultiplayerControllerNatives); \
	AMultiplayerHero::StaticClass(); \
	AMultiplayerHUD::StaticClass(); \
	GNativeLookupFuncs.Set(FName("MultiplayerHUD"), GMultiplayerAMultiplayerHUDNatives); \
	AMultiplayerLink::StaticClass(); \
	GNativeLookupFuncs.Set(FName("MultiplayerLink"), GMultiplayerAMultiplayerLinkNatives); \
	UPushableChannel::StaticClass(); \
	GNativeLookupFuncs.Set(FName("PushableChannel"), GMultiplayerUPushableChannelNatives); \
	URemotePlayer::StaticClass(); \
	GNativeLookupFuncs.Set(FName("RemotePlayer"), GMultiplayerURemotePlayerNatives); \
	UWorldChannel::StaticClass(); \
	GNativeLookupFuncs.Set(FName("WorldChannel"), GMultiplayerUWorldChannelNatives); \

#endif // MULTIPLAYER_NATIVE_DEFS

#ifdef NATIVES_ONLY
FNativeFunctionLookup GMultiplayerUDoorChannelNatives[] = 
{ 
	MAP_NATIVE(UDoorChannel, execOnBinaryPacket)
	MAP_NATIVE(UDoorChannel, execBroadcastDoorStates)
	MAP_NATIVE(UDoorChannel, execOnDoorDeny)
	MAP_NATIVE(UDoorChannel, execOnLocalDoorClose)
	MAP_NATIVE(UDoorChannel, execOnLocalDoorOpen)
	MAP_NATIVE(UDoorChannel, execTickSend)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerUEnemyChannelNatives[] = 
{ 
	MAP_NATIVE(UEnemyChannel, execFindEnemyByName)
	MAP_NATIVE(UEnemyChannel, execOnBinaryPacket)
	MAP_NATIVE(UEnemyChannel, execOnBinaryLoc)
	MAP_NATIVE(UEnemyChannel, execOnRequestEnemies)
	MAP_NATIVE(UEnemyChannel, execBroadcastSpawns)
	MAP_NATIVE(UEnemyChannel, execSendAllDeletes)
	MAP_NATIVE(UEnemyChannel, execSendEnemyDoorBreak)
	MAP_NATIVE(UEnemyChannel, execSendEnemyDoorBash)
	MAP_NATIVE(UEnemyChannel, execSendEnemyDoorDone)
	MAP_NATIVE(UEnemyChannel, execSendEnemyDoorOpen)
	MAP_NATIVE(UEnemyChannel, execSendSMTDirect)
	MAP_NATIVE(UEnemyChannel, execSendSMT)
	MAP_NATIVE(UEnemyChannel, execSendSpawn)
	MAP_NATIVE(UEnemyChannel, execTickSend)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerUHeroChannelNatives[] = 
{ 
	MAP_NATIVE(UHeroChannel, execOnBinaryPlayerLifecycle)
	MAP_NATIVE(UHeroChannel, execSendRequestPushables)
	MAP_NATIVE(UHeroChannel, execSendRequestDoors)
	MAP_NATIVE(UHeroChannel, execSendRequestEnemies)
	MAP_NATIVE(UHeroChannel, execSendDisconnect)
	MAP_NATIVE(UHeroChannel, execSendPlayerRespawned)
	MAP_NATIVE(UHeroChannel, execSendPlayerDied)
	MAP_NATIVE(UHeroChannel, execApplyLocomotionMode)
	MAP_NATIVE(UHeroChannel, execApplySpecialMoveTransition)
	MAP_NATIVE(UHeroChannel, execApplyCamcorderState)
	MAP_NATIVE(UHeroChannel, execOnBinaryPlayerEvent)
	MAP_NATIVE(UHeroChannel, execOnBinarySmtType)
	MAP_NATIVE(UHeroChannel, execOnBinaryCinematicAnim)
	MAP_NATIVE(UHeroChannel, execOnBinaryMesh)
	MAP_NATIVE(UHeroChannel, execOnBinaryHeadRot)
	MAP_NATIVE(UHeroChannel, execOnBinaryLoc)
	MAP_NATIVE(UHeroChannel, execSendPlayerKill)
	MAP_NATIVE(UHeroChannel, execSendPlayerThrow)
	MAP_NATIVE(UHeroChannel, execSendPlayerGrab)
	MAP_NATIVE(UHeroChannel, execSendPlayerHit)
	MAP_NATIVE(UHeroChannel, execSendCornerPeekData)
	MAP_NATIVE(UHeroChannel, execSendPickupState)
	MAP_NATIVE(UHeroChannel, execSendPickupStart)
	MAP_NATIVE(UHeroChannel, execSendSpecialMoveType)
	MAP_NATIVE(UHeroChannel, execSendCinematicAnimation)
	MAP_NATIVE(UHeroChannel, execSendMesh)
	MAP_NATIVE(UHeroChannel, execSendHeadRotation)
	MAP_NATIVE(UHeroChannel, execSendGlobalState)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerAMultiplayerControllerNatives[] = 
{ 
	MAP_NATIVE(AMultiplayerController, execNativeDestroyed)
	MAP_NATIVE(AMultiplayerController, execInterpolationFinished)
	MAP_NATIVE(AMultiplayerController, execInterpolationStarted)
	MAP_NATIVE(AMultiplayerController, execOnToggleCinematicMode)
	MAP_NATIVE(AMultiplayerController, execOnRecordingMarkerCompleted)
	MAP_NATIVE(AMultiplayerController, execOnLocalDoorClose)
	MAP_NATIVE(AMultiplayerController, execOnLocalDoorOpen)
	MAP_NATIVE(AMultiplayerController, execOnPickupKismetEvent)
	MAP_NATIVE(AMultiplayerController, execOnInventoryItemConsumed)
	MAP_NATIVE(AMultiplayerController, execNotifyPawnTouchedTrigger)
	MAP_NATIVE(AMultiplayerController, execNotifyEnemyDoorBreak)
	MAP_NATIVE(AMultiplayerController, execNotifyEnemyDoorBash)
	MAP_NATIVE(AMultiplayerController, execNativeNotifyEnemyDoorDone)
	MAP_NATIVE(AMultiplayerController, execNativeNotifyEnemyDoorOpen)
	MAP_NATIVE(AMultiplayerController, execNotifyDummyEnemySMT)
	MAP_NATIVE(AMultiplayerController, execNotifyDummyPlayerKill)
	MAP_NATIVE(AMultiplayerController, execNotifyDummyPlayerThrow)
	MAP_NATIVE(AMultiplayerController, execNotifyDummyPlayerGrab)
	MAP_NATIVE(AMultiplayerController, execNotifyDummyPlayerHit)
	MAP_NATIVE(AMultiplayerController, execDestroyRemoteEnemies)
	MAP_NATIVE(AMultiplayerController, execRemoveRemotePlayer)
	MAP_NATIVE(AMultiplayerController, execApplyPendingPushStates)
	MAP_NATIVE(AMultiplayerController, execIndexPushables)
	MAP_NATIVE(AMultiplayerController, execIndexEnemies)
	MAP_NATIVE(AMultiplayerController, execIndexDoors)
	MAP_NATIVE(AMultiplayerController, execNativeDestroyRemoteEnemies)
	MAP_NATIVE(AMultiplayerController, execNativeRemoveRemotePlayer)
	MAP_NATIVE(AMultiplayerController, execOnDisconnected)
	MAP_NATIVE(AMultiplayerController, execOnConnected)
	MAP_NATIVE(AMultiplayerController, execOnReceiveBinaryData)
	MAP_NATIVE(AMultiplayerController, execOnReceiveData)
	MAP_NATIVE(AMultiplayerController, execNativeSetHero)
	MAP_NATIVE(AMultiplayerController, execRegisterRemotePlayer)
	MAP_NATIVE(AMultiplayerController, execFindRemoteIndex)
	MAP_NATIVE(AMultiplayerController, execIsReady)
	MAP_NATIVE(AMultiplayerController, execIsConnected)
	MAP_NATIVE(AMultiplayerController, execNativeInit)
	MAP_NATIVE(AMultiplayerController, execNativeGetUsername)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerAMultiplayerHUDNatives[] = 
{ 
	MAP_NATIVE(AMultiplayerHUD, execAddNotification)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerAMultiplayerLinkNatives[] = 
{ 
	MAP_NATIVE(AMultiplayerLink, execNativeReloadConfig)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerUPushableChannelNatives[] = 
{ 
	MAP_NATIVE(UPushableChannel, execFindPushableByKey)
	MAP_NATIVE(UPushableChannel, execBroadcastPushableStates)
	MAP_NATIVE(UPushableChannel, execTickSend)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerURemotePlayerNatives[] = 
{ 
	MAP_NATIVE(URemotePlayer, execTick)
	{NULL, NULL}
};

FNativeFunctionLookup GMultiplayerUWorldChannelNatives[] = 
{ 
	MAP_NATIVE(UWorldChannel, execOnDisconnected)
	MAP_NATIVE(UWorldChannel, execOnBinaryWorldPacket)
	MAP_NATIVE(UWorldChannel, execOnBinaryNick)
	MAP_NATIVE(UWorldChannel, execOnPawnTouchedTrigger)
	MAP_NATIVE(UWorldChannel, execSendMatineeState)
	MAP_NATIVE(UWorldChannel, execSendRecordingMarker)
	MAP_NATIVE(UWorldChannel, execSendItemConsume)
	MAP_NATIVE(UWorldChannel, execSendPickupKismet)
	MAP_NATIVE(UWorldChannel, execSendPickupState)
	{NULL, NULL}
};

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(UDoorChannel,DoorChannel,ControllerOwner)
VERIFY_CLASS_OFFSET_NODIE(UDoorChannel,DoorChannel,HeroPawn)
VERIFY_CLASS_SIZE_NODIE(UDoorChannel)
VERIFY_CLASS_OFFSET_NODIE(UEnemyChannel,EnemyChannel,ControllerOwner)
VERIFY_CLASS_OFFSET_NODIE(UEnemyChannel,EnemyChannel,HeroPawn)
VERIFY_CLASS_SIZE_NODIE(UEnemyChannel)
VERIFY_CLASS_OFFSET_NODIE(UHeroChannel,HeroChannel,ControllerOwner)
VERIFY_CLASS_OFFSET_NODIE(UHeroChannel,HeroChannel,LastPickupLoc)
VERIFY_CLASS_SIZE_NODIE(UHeroChannel)
VERIFY_CLASS_OFFSET_NODIE(AMultiplayerController,MultiplayerController,HeroChannel)
VERIFY_CLASS_OFFSET_NODIE(AMultiplayerController,MultiplayerController,CSAActBlacklist)
VERIFY_CLASS_SIZE_NODIE(AMultiplayerController)
VERIFY_CLASS_SIZE_NODIE(AMultiplayerHero)
VERIFY_CLASS_OFFSET_NODIE(AMultiplayerHUD,MultiplayerHUD,MaxNickDisplay)
VERIFY_CLASS_OFFSET_NODIE(AMultiplayerHUD,MultiplayerHUD,Notifications)
VERIFY_CLASS_SIZE_NODIE(AMultiplayerHUD)
VERIFY_CLASS_SIZE_NODIE(AMultiplayerLink)
VERIFY_CLASS_OFFSET_NODIE(UPushableChannel,PushableChannel,ControllerOwner)
VERIFY_CLASS_OFFSET_NODIE(UPushableChannel,PushableChannel,HeroPawn)
VERIFY_CLASS_SIZE_NODIE(UPushableChannel)
VERIFY_CLASS_OFFSET_NODIE(URemotePlayer,RemotePlayer,ControllerOwner)
VERIFY_CLASS_OFFSET_NODIE(URemotePlayer,RemotePlayer,LastRemotePickupLoc)
VERIFY_CLASS_SIZE_NODIE(URemotePlayer)
VERIFY_CLASS_OFFSET_NODIE(UWorldChannel,WorldChannel,ControllerOwner)
VERIFY_CLASS_OFFSET_NODIE(UWorldChannel,WorldChannel,HeroPawn)
VERIFY_CLASS_SIZE_NODIE(UWorldChannel)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
