/*=============================================================================
    Multiplayer.h
=============================================================================*/

#pragma once

#include "Engine.h"
#include "EngineClasses.h"
#include "UnIpDrv.h"
#include "IpDrvClasses.h"
#include "OLGame.h"

// Native structs referenced by AMultiplayerController — must be declared before MultiplayerClasses.h.
// Fields match the UC struct declarations in MultiplayerController.uc.
struct FPendingDoorState
{
    INT   KeyX, KeyY, KeyZ;
    FLOAT Angle;
};
struct FPendingPushState
{
    INT   KeyX, KeyY, KeyZ;
    FLOAT Displacement;
};
struct FRemoteEnemyState
{
    FString         NetName;
    AOLEnemyPawn*   DummyEnemy;
    INT             OwnerID;
    FVector         TargetLoc;
    FRotator        TargetRot;
    FVector         TargetVel;
    UBOOL           bAnimating;
};

// UC struct NotificationEntry (MultiplayerHUD.uc) — UMake doesn't emit struct bodies,
// so we declare FNotificationEntry manually before MultiplayerClasses.h uses it.
struct FNotificationEntry
{
    FString Text;
    FLOAT   ExpireTime;
};

// Generated by UMake after first compile with native declarations
#include "MultiplayerClasses.h"

// ============================================================================
// FMpConnection — persistent UDP connection that survives map transitions.
// Inherits FUdpLink directly (owns the socket).
// Lives as a global singleton; never destroyed while the process runs.
// Ticked via FMpConnectionTicker which is registered after engine init.
// ============================================================================

class FMpConnection : public FUdpLink
{
public:
    // Session state
    UBOOL   bIsConnected;
    UBOOL   bIsHandshaked;
    UBOOL   bResolved;
    INT     LocalPlayerID;
    INT     HelloAttempt;
    FLOAT   LastReceivedTime;
    FLOAT   HelloTimer;         // seconds until next HELLO retry
    FLOAT   HeartbeatTimer;     // seconds until next heartbeat check

    // Server address (filled on Resolve)
    FIpAddr ServerAddr;

    // Config (read from DefaultMultiplayer.ini on first connect)
    FString IP;
    FString UdpPort;
    FString Username;
    FString RoomCode;
    FString Password;
    UBOOL   SyncInteractable;
    UBOOL   SyncEnemies;
    UBOOL   SyncMatinees;
    UBOOL   SyncPickups;

    // Initialized flag — set after first LoadConfig(); avoids re-reading ini.

    // Persistent player registry — survives map transitions.
    // Keyed by PlayerID; populated on NICK, cleared on DISCONNECT.
    struct FRemoteNick { INT PlayerID; FString Username; };
    TArray<FRemoteNick> KnownPlayers;

    // Persistent server info — survives map transitions.
    FString ServerName;
    INT     OnlineCount;

    FLOAT   PingTimer;

    FMpConnection()
        : bIsConnected(FALSE), bIsHandshaked(FALSE), bResolved(FALSE)
        , LocalPlayerID(0), HelloAttempt(0), LastReceivedTime(0.f)
        , HelloTimer(0.f), HeartbeatTimer(5.f)
        , SyncInteractable(TRUE), SyncEnemies(TRUE)
        , SyncMatinees(TRUE), SyncPickups(TRUE)
        , OnlineCount(0), PingTimer(5.f)
    {
        appMemzero(&ServerAddr, sizeof(ServerAddr));
    }

    // Load settings from DefaultMultiplayer.ini ([Multiplayer.MultiplayerLink]).
    void LoadConfig();

    // Kick off DNS resolve + bind. Safe to call multiple times (no-op if already resolved).
    void Connect();

    // Send raw bytes prepending [type(1)][player_id LE4]. Safe to call any time.
    void SendBinary(BYTE* Data, INT Count);

    // Send a text line to the server (legacy path).
    void SendText(const FString& Line);

    // FUdpLink override — receives all incoming UDP datagrams.
    virtual void OnReceivedData(FIpAddr SrcAddr, BYTE* Data, INT Count);

    // Send DISCONNECT packet to server and reset connection state.
    void Disconnect();

    // Called every frame by FMpConnectionTicker.
    void Tick(FLOAT DeltaTime);
};

extern FMpConnection  GMpConn;
extern FResolveInfo*  GResolveInfo;

// Registered as FTickableObject after engine init (in NativeInit).
// Forwards Tick to GMpConn so the global singleton doesn't self-register at static init time.
class FMpConnectionTicker : public FTickableObject
{
public:
    virtual void  Tick(FLOAT DeltaTime)        { GMpConn.Tick(DeltaTime); }
    virtual UBOOL IsTickable() const           { return TRUE; }
    virtual UBOOL IsTickableWhenPaused() const { return FALSE; }
};

// Global channel context — set by MultiplayerController::NativeInit each map load.
extern AMultiplayerController* GMultiplayerController;
extern AOLHero*                GMultiplayerHero;

// CanSend — connected, handshaked, local hero present
// CanReceive — connected (used before hero spawns)
FORCEINLINE UBOOL CanSend()
{
    return GMultiplayerHero != NULL
        && GMpConn.bIsConnected
        && GMpConn.bIsHandshaked;
}
FORCEINLINE UBOOL CanReceive()
{
    return GMpConn.bIsConnected;
}
